Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'

-- Deliveries
Config.ShopsInvJsonFile = './json/shops-inventory.json'
Config.TruckDeposit = 125
Config.MaxDeliveries = 20
Config.DeliveryPrice = 1000
Config.RewardItem = 'tosti'
Config.Fuel = 'LegacyFuel'

Config.DeliveryLocations = {
    ['main'] = { label = 'Chronopost', coords = vector4(69.0862, 127.6753, 79.2123, 156.7736) },
    ['vehicleWithdraw'] = vector4(71.9318, 120.8389, 79.0823, 160.5110),
    ['vehicleDeposit'] = vector3(62.7282, 124.9846, 79.0926),
    ['stores'] = {} -- auto generated
}

Config.Vehicles = {
    ['chrono1'] = { ['label'] = 'chrono1', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
    ['chrono2'] = { ['label'] = 'chrono1', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
}

Config.Products = {
    ['normal'] = {
        { name = 'tosti',         price = 200,   amount = 50 },
        { name = 'water_bottle',  price = 80,   amount = 50 },
        { name = 'twerks_candy',  price = 180,   amount = 50 },
        { name = 'snikkel_candy', price = 180,   amount = 50 },
        { name = 'sandwich',      price = 200,   amount = 50 },
        { name = 'beer',          price = 100,   amount = 50 },
        { name = 'whiskey',       price = 120,  amount = 50 },
        { name = 'vodka',         price = 120,  amount = 50 },
        { name = 'bandage',       price = 100, amount = 50 },
        { name = 'kq_outfitbag',  price = 1500,   amount = 50 },
        { name = 'repairkit',  price = 3500,   amount = 50 },
        { name = 'trimming_scissors', price = 1500, amount = 50},
        { name = 'skateboard', price = 2500, amount = 50},
        { name = 'pickaxe', price = 250, amount = 50},
        { name = 'axe', price = 250, amount = 50}
    },
    ['liquor'] = {
        { name = 'beer',    price = 7,  amount = 50 },
        { name = 'whiskey', price = 10, amount = 50 },
        { name = 'vodka',   price = 12, amount = 50 },
    },
    ['weedshop'] = {
        { name = 'joint',          price = 10,  amount = 50 },
        { name = 'weapon_poolcue', price = 100, amount = 50 },
        { name = 'weed_nutrition', price = 20,  amount = 50 },
        { name = 'empty_weed_bag', price = 2,   amount = 1000 },
        { name = 'rolling_paper',  price = 2,   amount = 1000 },
    },
    ['gearshop'] = {
        { name = 'diving_gear', price = 2500, amount = 10 },
        { name = 'jerry_can',   price = 200,  amount = 50 },
    },
    ['leisureshop'] = {
        { name = 'parachute',   price = 2500, amount = 10 },
        { name = 'binoculars',  price = 50,   amount = 50 },
        { name = 'diving_gear', price = 2500, amount = 10 },
        { name = 'diving_fill', price = 500,  amount = 10 },
    },
    ['weapons'] = {
        { name = 'weapon_knife',         price = 250,  amount = 250 },
        { name = 'weapon_bat',           price = 250,  amount = 250 },
        { name = 'weapon_hatchet',       price = 250,  amount = 250 },
        { name = 'pistol_ammo',          price = 250,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_pistol',        price = 2500, amount = 5,   requiredLicense = 'weapon' },
        { name = 'weapon_snspistol',     price = 1500, amount = 5,   requiredLicense = 'weapon' },
        { name = 'weapon_vintagepistol', price = 4000, amount = 5,   requiredLicense = 'weapon' },
    },
    ['blackmarket'] = {
        { name = 'security_card_01',  price = 5000, amount = 50 },
        { name = 'security_card_02',  price = 5000, amount = 50 },
        { name = 'advanced_lockpick', price = 5000, amount = 50 },
        { name = 'electronickit',     price = 5000, amount = 50 },
        { name = 'gatecrack',         price = 5000, amount = 50 },
        { name = 'thermite',          price = 5000, amount = 50 },
        { name = 'trojan_usb',        price = 5000, amount = 50 },
        { name = 'drill',             price = 5000, amount = 50 },
        { name = 'radioscanner',      price = 5000, amount = 50 },
        { name = 'cryptostick',       price = 5000, amount = 50 },
        { name = 'joint',             price = 5000, amount = 50 },
        { name = 'cokebaggy',         price = 5000, amount = 50 },
        { name = 'crack_baggy',       price = 5000, amount = 50 },
        { name = 'xtcbaggy',          price = 5000, amount = 50 },
        { name = 'coke_brick',        price = 5000, amount = 50 },
        { name = 'weed_brick',        price = 5000, amount = 50 },
        { name = 'coke_small_brick',  price = 5000, amount = 50 },
        { name = 'oxy',               price = 5000, amount = 50 },
        { name = 'meth',              price = 5000, amount = 50 },
        { name = 'weed_whitewidow',   price = 5000, amount = 50 },
        { name = 'weed_skunk',        price = 5000, amount = 50 },
        { name = 'weed_purplehaze',   price = 5000, amount = 50 },
        { name = 'weed_ogkush',       price = 5000, amount = 50 },
        { name = 'weed_amnesia',      price = 5000, amount = 50 },
        { name = 'weed_ak47',         price = 5000, amount = 50 },
        { name = 'markedbills',       price = 5000, amount = 50, info = { worth = 5000 } },
    },
    ['prison'] = {
        { name = 'sandwich',     price = 4, amount = 50 },
        { name = 'water_bottle', price = 4, amount = 50 },
    },
    ['police'] = {
        { name = 'weapon_pistol',       price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_stungun',      price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_pumpshotgun',  price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_smg',          price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_MACRO_02', label = '1x Scope' }, { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_carbinerifle', price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', label = '3x Scope' } } } },
        { name = 'weapon_nightstick',   price = 0, amount = 50 },
        { name = 'weapon_flashlight',   price = 0, amount = 50 },
        { name = 'pistol_ammo',         price = 0, amount = 50 },
        { name = 'smg_ammo',            price = 0, amount = 50 },
        { name = 'shotgun_ammo',        price = 0, amount = 50 },
        { name = 'rifle_ammo',          price = 0, amount = 50 },
        { name = 'handcuffs',           price = 0, amount = 50 },
        { name = 'empty_evidence_bag',  price = 0, amount = 50 },
        { name = 'police_stormram',     price = 0, amount = 50 },
        { name = 'armor',               price = 0, amount = 50 },
        { name = 'radio',               price = 0, amount = 50 },
        { name = 'heavyarmor',          price = 0, amount = 50 },
    },
    ['ambulance'] = {
        { name = 'radio',                   price = 0, amount = 50 },
        { name = 'bandage',                 price = 0, amount = 50 },
        { name = 'painkillers',             price = 0, amount = 50 },
        { name = 'firstaid',                price = 0, amount = 50 },
        { name = 'weapon_flashlight',       price = 0, amount = 50 },
        { name = 'weapon_fireextinguisher', price = 0, amount = 50 },
    },
    ['mechanic'] = {
        { name = 'veh_toolbox',       price = 600, amount = 50 },
        { name = 'veh_brakes',        price = 600, amount = 50 },
        { name = 'veh_engine',        price = 600, amount = 50 },
        { name = 'veh_suspension',    price = 600, amount = 50 },
        { name = 'veh_transmission',  price = 600, amount = 50 },
        { name = 'veh_turbo',         price = 600, amount = 50 },
        { name = 'veh_interior',      price = 600, amount = 50 },
        { name = 'veh_exterior',      price = 600, amount = 50 },
        { name = 'veh_wheels',        price = 600, amount = 50 },
        { name = 'veh_neons',         price = 600, amount = 50 },
        { name = 'veh_xenons',        price = 600, amount = 50 },
        { name = 'veh_tint',          price = 600, amount = 50 },
        { name = 'veh_plates',        price = 600, amount = 50 },
        { name = 'nitrous',           price = 600, amount = 50 },
        { name = 'repairkit',         price = 1000, amount = 50 },
        { name = 'advancedrepairkit', price = 2000, amount = 50 },
        { name = 'tirerepairkit',     price = 500, amount = 50 },
    },
    ['phonestore'] = {
        { name = 'classic_phone',       price = 2500, amount = 50 },
        { name = 'black_phone',         price = 2500, amount = 50 },
        { name = 'blue_phone',        price = 2500, amount = 50 },
        { name = 'gold_phone',        price = 2500, amount = 50 },
        { name = 'red_phone',    price = 2500, amount = 50 },
        { name = 'green_phone',  price = 2500, amount = 50 },
        { name = 'greenlight_phone',         price = 2500, amount = 50 },
        { name = 'pink_phone',      price = 2500, amount = 50 },
        { name = 'white_phone',      price = 2500, amount = 50 },
    },
    ['fruit'] = {
        { name = 'apple',       price = 120, amount = 50 },
        { name = 'banana',         price = 120, amount = 50 },
        { name = 'pear',        price = 120, amount = 50 },
        { name = 'orange',        price = 120, amount = 50 },
        { name = 'pineapple',    price = 120, amount = 50 },
    },
    ['legumes'] = {
        { name = 'onion',       price = 120, amount = 50 },
        { name = 'red_onion',         price = 120, amount = 50 },
        { name = 'potatoes',        price = 120, amount = 50 },
        { name = 'salad',        price = 120, amount = 50 },
        { name = 'tomato',    price = 120, amount = 50 },
    },
    ['viandes'] = {
        { name = 'steakhacher',       price = 180, amount = 50 },
        { name = 'chorizo',       price = 130, amount = 50 },
        { name = 'jambon',       price = 180, amount = 50 },
    },
    ['distributeur'] = {
        { name = 'coca', price = 150, amount = 50 },
        { name = 'icetea', price = 150, amount = 50 },
        { name = 'sprite', price = 150, amount = 50 },
        { name = 'redbull', price = 160, amount = 50 },
        { name = 'orangina', price = 150, amount = 50 },
        { name = 'fanta', price = 150, amount = 50 },
        { name = 'monster', price = 150, amount = 50 },
    },
    ['boulangerie'] = {
        { name = 'pateapizza',       price = 110, amount = 50 },
        { name = 'painhamburger',       price = 110, amount = 50 },
    },
    ['propstore'] = {
        { name = "yogamat_blue", price = 200, amount = 50 },
        { name = "yogamat_black", price = 200, amount = 50 },
        { name = "yogamat_red", price = 200, amount = 50 },
        { name = "camp_chair_green", price = 200, amount = 50 },
        { name = "camp_chair_blue", price = 200, amount = 50 },
        { name = "camp_chair_plaid", price = 200, amount = 50 },
        { name = "plastic_chair", price = 200, amount = 50 },
        { name = "folding_chair", price = 200, amount = 50 },
        { name = "roadworkbarrier", price = 200, amount = 50 },
        { name = "roadclosedbarrier", price = 200, amount = 50 },
        { name = "constructionbarrier", price = 200, amount = 50 },
        { name = "constructionbarrier2", price = 200, amount = 50 },
        { name = "constructionbarrier3", price = 200, amount = 50 },
        { name = "roadconebig", price = 200, amount = 50 },
        { name = "roadcone", price = 200, amount = 50 },
        { name = "roadpole", price = 200, amount = 50 },
        { name = "worklight", price = 200, amount = 50 },
        { name = "worklight2", price = 200, amount = 50 },
        { name = "worklight3", price = 200, amount = 50 },
        { name = "constructiongenerator", price = 500, amount = 50 },
        { name = "trafficdevice", price = 500, amount = 50 },
        { name = "trafficdevice2", price = 200, amount = 50 },
        { name = "tent", price = 200, amount = 50 },
        { name = "tent2", price = 200, amount = 50 },
        { name = "tent3", price = 200, amount = 50 },
        { name = "tristarttable", price = 200, amount = 50 },
        { name = "tristartbanner", price = 200, amount = 50 },
        { name = "trifinishbanner", price = 200, amount = 50 },
        { name = "plastictable", price = 200, amount = 50 },
        { name = "plastictable2", price = 200, amount = 50 },
        { name = "woodtable", price = 200, amount = 50 },
        { name = "woodtable2", price = 200, amount = 50 },
        { name = "beachtowel", price = 200, amount = 50 },
        { name = "beachumbrella", price = 200, amount = 50 },
        { name = "beachumbrella2", price = 200, amount = 50 },
        { name = "beachumbrella3", price = 200, amount = 50 },
        { name = "beachumbrella4", price = 200, amount = 50 },
        { name = "beachball", price = 200, amount = 50 },
        { name = "greenscreen", price = 200, amount = 50 },
        { name = "ropebarrier", price = 200, amount = 50 },
        { name = "largesoccerball", price = 2000, amount = 50 },
        { name = "soccerball", price = 200, amount = 50 },
        { name = "sleepingbag", price = 200, amount = 50 },
        { name = "ramp1", price = 5000, amount = 50 },
        { name = "ramp2", price = 5000, amount = 50 },
        { name = "ramp3", price = 5000, amount = 50 },
        { name = "ramp4", price = 5000, amount = 50 },
        { name = "ramp5", price = 5000, amount = 50 },
        { name = "skateramp", price = 2500, amount = 50 },
        { name = "meshfence1", price = 200, amount = 50 },
        { name = "meshfence2", price = 200, amount = 50 },
        { name = "meshfence3", price = 200, amount = 50 },
        { name = "canopy1", price = 200, amount = 50 },
        { name = "canopy2", price = 200, amount = 50 },
        { name = "canopy3", price = 200, amount = 50 },
        { name = "stepladder", price = 200, amount = 50 },
        { name = "shoppingcart1", price = 200, amount = 50 },
        { name = "shoppingcart2", price = 200, amount = 50 },
        { name = "shoppingcart3", price = 200, amount = 50 },
        { name = "shoppingcart4", price = 200, amount = 50 },
        { name = "wheelbarrow", price = 200, amount = 50 },
        { name = "warehousetrolly1", price = 200, amount = 50 },
        { name = "warehousetrolly2", price = 200, amount = 50 },
        { name = "roomtrolly", price = 200, amount = 50 },
        { name = "janitorcart1", price = 200, amount = 50 },
        { name = "janitorcart2", price = 200, amount = 50 },
        { name = "metalcart", price = 200, amount = 50 },
        { name = "teacart", price = 200, amount = 50 },
        { name = "drinkcart", price = 200, amount = 50 },
        { name = "handtruck1", price = 200, amount = 50 },
        { name = "handtruck2", price = 200, amount = 50 },
        { name = "trashbin", price = 200, amount = 50 },
        { name = "cot", price = 200, amount = 50 },
        { name = "mopbucket", price = 200, amount = 50 },
        { name = "lawnmower", price = 200, amount = 50 },
        { name = "toolchest", price = 200, amount = 50 },
        { name = "carjack", price = 200, amount = 50 },
        { name = "waterbarrel", price = 200, amount = 50 },
        { name = "cargobox1", price = 200, amount = 50 },
        { name = "cargobox2", price = 200, amount = 50 },
        { name = "cargobox3", price = 200, amount = 50 },
        { name = "cargobox4", price = 200, amount = 50 },
        { name = "cargobox5", price = 200, amount = 50 },
        { name = "cargobox6", price = 200, amount = 50 },
        { name = "cargobox7", price = 200, amount = 50 },
        { name = "cargobox8", price = 200, amount = 50 },
        { name = "pallet1", price = 200, amount = 50 },
        { name = "pallet2", price = 200, amount = 50 },
        { name = "pallet3", price = 200, amount = 50 },
        { name = "pallet4", price = 200, amount = 50 },
        { name = "pallet5", price = 200, amount = 50 },
        { name = "crate1", price = 200, amount = 50 },
        { name = "crate2", price = 200, amount = 50 },
        { name = "crate3", price = 200, amount = 50 },
        { name = "crate4", price = 200, amount = 50 },
        { name = "crate5", price = 200, amount = 50 },
        { name = "snowman1", price = 200, amount = 50 },
        { name = "snowman2", price = 200, amount = 50 },
        { name = "snowman3", price = 200, amount = 50 },
        { name = "snowman4", price = 200, amount = 50 },
        { name = "xmastree1", price = 200, amount = 50 },
        { name = "xmastree2", price = 200, amount = 50 },
        { name = "candycane", price = 200, amount = 50 },
        { name = "xmaspresent", price = 200, amount = 50 },
        { name = "balise", price = 200, amount = 50 },
        { name = "barriereroutebaree", price = 200, amount = 50 },
        { name = "barriere", price = 200, amount = 50 },
        { name = "cone", price = 200, amount = 50 },
        { name = "panneauaccident", price = 200, amount = 50 },
        { name = "panneauattention", price = 200, amount = 50 },
        { name = "panneauhaltegendarmerie", price = 200, amount = 50 },
        { name = "panneauinondation", price = 200, amount = 50 },
        { name = "panneausensinterdit", price = 200, amount = 50 },
        { name = "panneautourneradroite", price = 200, amount = 50 },
        { name = "panneautourneragauche", price = 200, amount = 50 },
        { name = "panneautravaux", price = 200, amount = 50 },
        { name = "routebaree", price = 200, amount = 50 }
    },
    ['tabac'] = {
        { name = 'rolling_paper',       price = 110, amount = 50 },
        { name = 'lighter',       price = 110, amount = 50 },
        { name = 'booster151',       price = 850, amount = 50 },
        { name = 'finescale',       price = 110, amount = 50 },
    },
    ['kfc'] = {
        { name = 'glacekfc',          price = 110, amount = 50, requiredJob = 'kfc'},
        { name = 'fritekfc',          price = 110, amount = 50, requiredJob = 'kfc'},
        { name = 'nuggetskfc',        price = 110, amount = 50, requiredJob = 'kfc'},
        { name = 'burgerpoulet',      price = 110, amount = 50, requiredJob = 'kfc'},
        { name = 'coca',              price = 110, amount = 50, requiredJob = 'kfc'},
        { name = 'icetea',            price = 110, amount = 50, requiredJob = ' kfc'},
        { name = 'redbull',           price = 110, amount = 50, requiredJob = ' kfc'},
        { name = 'fanta',             price = 110, amount = 50, requiredJob = ' kfc'},
        { name = 'sprite',            price = 110, amount = 50, requiredJob = ' kfc'},
        { name = 'monster',           price = 110, amount = 50, requiredJob = ' kfc'},
        { name = 'orangina',          price = 110, amount = 50, requiredJob = ' kfc'}
    },
    ['burgerking'] = {
        { name = 'glaceburgerking',   price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'friteburgerking',   price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'nuggetsburgerking', price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'triplechesse',      price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'coca',              price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'icetea',            price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'redbull',           price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'fanta',             price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'sprite',            price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'monster',           price = 110, amount = 50, requiredJob = 'burgerking'},
        { name = 'orangina',          price = 110, amount = 50, requiredJob = 'burgerking'}
    },
    ['otacos'] = {
        { name = 'glacetacos',        price = 850, amount = 50, requiredJob = 'otacos' },
        { name = 'fritetacos',        price = 110, amount = 50, requiredJob = 'otacos' },
        { name = 'tacos',             price = 110, amount = 50, requiredJob = 'otacos' },
        { name = 'coca',              price = 110, amount = 50, requiredJob = 'otacos' },
        { name = 'icetea',            price = 110, amount = 50, requiredJob = 'otacos' },
        { name = 'redbull',           price = 110, amount = 50, requiredJob = 'otacos' },
        { name = 'fanta',             price = 110, amount = 50, requiredJob = 'otacos' },
        { name = 'sprite',            price = 110, amount = 50, requiredJob = 'otacos' },
        { name = 'monster',           price = 110, amount = 50, requiredJob = 'otacos' },
        { name = 'orangina',          price = 110, amount = 50, requiredJob = 'otacos' }
    },
    ['samu_75'] = {
        { name = 'firstaid',        price = 1, amount = 50, requiredJob = 'samu_75' },
        { name = 'bandage',        price = 1, amount = 50, requiredJob = 'samu_75' },
        { name = 'ifaks',             price = 1, amount = 50, requiredJob = 'samu_75' },
        { name = 'painkillers',              price = 1, amount = 50, requiredJob = 'samu_75' },
        { name = 'walkstick',            price = 1, amount = 50, requiredJob = 'samu_75' }
    },
    ['pompiers_de_paris'] = {
        { name = 'firstaid',        price = 0, amount = 500, requiredJob = 'pompiers_de_paris' },
        { name = 'bandage',        price = 0, amount = 500, requiredJob = 'pompiers_de_paris' },
        { name = 'ifaks',             price = 0, amount = 500, requiredJob = 'pompiers_de_paris' },
        { name = 'painkillers',              price = 0, amount = 500, requiredJob = 'pompiers_de_paris' }
    },
}

Config.Locations = { 
    -- 24/7 Locations
    ['247supermarket'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(24.47, -1346.62, 29.5, 271.66),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(26.45, -1315.51, 29.62, 0.07),
        ['useStock'] = true
    },

    ['247supermarket2'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },

    ['247supermarket3'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },

    ['247supermarket4'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },

    ['247supermarket5'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },

    ['247supermarket6'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(549.13, 2670.85, 42.16, 99.39),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(541.54, 2663.53, 42.17, 120.51)
    },

    ['247supermarket7'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },

    ['247supermarket8'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(2556.66, 380.84, 108.62, 356.67),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2553.24, 399.73, 108.56, 344.86)
    },

    ['247supermarket9'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(372.66, 326.98, 103.57, 253.73),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    -- Carrefour City Locations
    ['ltdgasoline'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-40.51, -1747.45, 29.29, 326.39)
    },

    ['ltdgasoline2'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(-706.06, -913.97, 19.22, 88.04),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-702.89, -917.44, 19.21, 181.96)
    },

    ['ltdgasoline3'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },

    ['ltdgasoline4'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(1164.71, -322.94, 69.21, 101.72),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1160.62, -312.06, 69.28, 3.77)
    },

    ['ltdgasoline5'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },

    -- Rob's Liquor Locations
    ['robsliquor'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },

    ['robsliquor2'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },

    ['robsliquor3'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },

    ['robsliquor4'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },

    ['robsliquor5'] = {
        ['label'] = 'Carrefour City',
        ['coords'] = vector4(1134.2, -982.91, 46.42, 277.24),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    ['propstore'] = {
        ['label'] = 'Magasin d\'Accessoires',
        ['coords'] = vector4(-580.49, -1001.42, 22.33, 268.43),
        ['ped'] = 'a_f_m_eastsa_02',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-box',
        ['targetLabel'] = 'Magasin d\'Accessoires',
        ['products'] = Config.Products['propstore'],
        ['showblip'] = true,
        ['blipsprite'] = 478,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 3,
    },
    ['norauto'] = {
        ['label'] = 'Norauto Shop',
        ['coords'] = vector4(844.11, -907.15, 25.25, 92.86),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Norauto Shop',
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(843.43, -907.17, 25.25, 273.13),
        ['requiredJob'] = 'norauto',
    },
    ['midas'] = {
        ['label'] = 'Midas Fourniture',
        ['coords'] = vector4(-933.74, -2058.45, 9.5, 61.09),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Midas Fourniture',
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-933.74, -2058.45, 9.5, 61.09),
        ['requiredJob'] = 'midas',
    },

    ['police_nationale'] = {
        ['label'] = 'Armurerie Police Nationale',
        ['coords'] = vector4(377.32, -1611.11, 29.34, 231.69),
        ['ped'] = 'mp_m_securoguard_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Armurerie',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(377.32, -1611.11, 29.34, 231.69),
        ['requiredJob'] = 'police_nationale',
    },
    ['gendarmerie_nationale'] = {
        ['label'] = 'Armurerie Gendarmerie Nationale',
        ['coords'] = vector4(-826.97, 6159.71, 9.47, 145.49),
        ['ped'] = 'mp_m_securoguard_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Armurerie',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(-826.97, 6159.71, 9.47, 145.49),
        ['requiredJob'] = 'gendarmerie_nationale',
    },

    ['ambulance'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(309.93, -602.94, 43.29, 71.0820),
        ['ped'] = 's_m_m_doctor_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(283.5821, -614.8570, 43.3792, 159.2903),
        ['requiredJob'] = 'ambulance'
    },

    ['mechanic2'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(1189.36, 2641.00, 38.44, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(1189.9852, 2651.1873, 37.8351, 317.7137),
        ['requiredJob'] = 'mechanic2'
    },

    ['mechanic3'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-1156.56, -1999.85, 13.19, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-1131.9661, -1972.0144, 13.1603, 358.8637),
        ['requiredJob'] = 'mechanic3'
    },

    ['bennys'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-195.80, -1318.24, 31.08, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-232.5028, -1311.7202, 31.2960, 180.3716),
        ['requiredJob'] = 'bennys'
    },

    ['beeker'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(100.92, 6616.00, 32.47, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(119.3033, 6626.7358, 31.9558, 46.1566),
        ['requiredJob'] = 'beeker'
    },

    ['prison'] = {
        ['label'] = 'Canteen Shop',
        ['coords'] = vector4(1777.59, 2560.52, 44.62, 187.83),
        ['ped'] = false,
        ['products'] = Config.Products['prison'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1845.8175, 2585.9312, 45.6721, 96.7577)
    },

    ['blackmarket'] = {
        ['label'] = 'Black Market',
        ['coords'] = vector4(-594.7032, -1616.3647, 33.0105, 170.6846),
        ['ped'] = 'a_m_y_smartcaspat_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-clipboard',
        ['targetLabel'] = 'Carrefour City',
        ['products'] = Config.Products['blackmarket'],
        ['delivery'] = vector4(-428.6385, -1728.1962, 19.7838, 75.6646)
    },

    ['phonestore'] = {
        ['label'] = 'Phone Store',
        ['coords'] = vector4(-1036.66, -2478.63, 20.34, 247.48),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Telephone',
        ['products'] = Config.Products['phonestore'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1035.24, -2478.85, 20.34, 59.87)
    },
    ['phonestore2'] = {
        ['label'] = 'Phone Store',
        ['coords'] = vector4(-1039.68, -2484.0, 20.34, 250.62),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Telephone',
        ['products'] = Config.Products['phonestore'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1038.47, -2484.65, 20.34, 61.41)
    },
    ['Fruit'] = {
        ['label'] = 'Fruit',
        ['coords'] = vector4(74.51, -1743.4, 29.29, 247.2),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Fruit',
        ['products'] = Config.Products['fruit'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(76.0, -1743.52, 29.29, 85.31)
    },
    ['legumes'] = {
        ['label'] = 'Legumes',
        ['coords'] = vector4(71.4, -1747.15, 29.29, 221.36),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Legumes',
        ['products'] = Config.Products['legumes'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(71.98, -1748.85, 29.29, 16.29),
        ['requiredJob'] = {'kfc', 'burgerking', 'pizza'}
    },
    ['viandes'] = {
        ['label'] = 'Viandes',
        ['coords'] = vector4(78.04, -1748.51, 29.29, 53.17),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Viandes',
        ['products'] = Config.Products['viandes'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(77.05, -1747.53, 29.29, 230.27),
        ['requiredJob'] = {'kfc', 'burgerking', 'pizza'}
    },
    ['boulangerie'] = {
        ['label'] = 'Boulangerie',
        ['coords'] = vector4(70.29, -1758.14, 29.29, 55.33),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Boulangerie',
        ['products'] = Config.Products['boulangerie'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(69.14, -1757.38, 29.29, 234.35),
        ['requiredJob'] = {'kfc', 'burgerking', 'pizza'}
    },
    ['tabac'] = {
        ['label'] = 'Tabac',
        ['coords'] = vector4(63.85, -1745.63, 29.29, 297.13),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Tabac',
        ['products'] = Config.Products['tabac'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(63.85, -1745.63, 29.29, 297.13),
        ['requiredJob'] = 'tabac'
    },
    ['kfc'] = {
        ['label'] = 'KFC',
        ['coords'] = vector4(69.11, -1742.06, 29.29, 52.7),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'KFC',
        ['products'] = Config.Products['kfc'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(69.11, -1742.06, 29.29, 52.7),
        ['requiredJob'] = 'kfc'
    },
    ['burgerking'] = {
        ['label'] = 'Burgerking',
        ['coords'] = vector4(71.42, -1740.54, 29.29, 16.14),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Burgerking',
        ['products'] = Config.Products['burgerking'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(71.42, -1740.54, 29.29, 16.14),
        ['requiredJob'] = 'burgerking'
    },
    ['otacos'] = {
        ['label'] = 'Otacos',
        ['coords'] = vector4(68.12, -1744.59, 29.29, 98.49),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Otacos',
        ['products'] = Config.Products['otacos'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(68.12, -1744.59, 29.29, 98.49),
        ['requiredJob'] = 'otacos'
    },
    ['samu_75'] = {
        ['label'] = 'Samu',
        ['coords'] = vector4(-1830.66, -381.36, 49.4, 61.85),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Samu',
        ['products'] = Config.Products['samu_75'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1830.66, -381.36, 49.4, 61.85),
    },
    ['pompiers_de_paris'] = {
        ['label'] = 'Pompier',
        ['coords'] = vector4(1213.89, -1486.39, 34.69, 114.59),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Pompier',
        ['products'] = Config.Products['pompiers_de_paris'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1213.26, -1486.29, 34.69, 264.39),
    },
}
Config.Shops = {
    ['distributeur'] = {
        ['label'] = 'Distributeur',
        ['props'] = { 
            'prop_vend_soda_01', 
            'prop_vend_soda_02' 
        },
        ['targetIcon'] = 'fas fa-shopping-cart',  -- vector4(-1830.66, -381.36, 49.4, 61.85)
        ['targetLabel'] = 'Utiliser le distributeur',
        ['products'] = {
            { name = 'coca', price = 600, amount = 50 },
            { name = 'icetea', price = 600, amount = 50 },
            { name = 'sprite', price = 600, amount = 50 },
            { name = 'redbull', price = 600, amount = 50 },
            { name = 'orangina', price = 600, amount = 50 },
            { name = 'fanta', price = 600, amount = 50 },
            { name = 'monster', price = 600, amount = 50 },
        },
        ['showblip'] = false
    }
}