local utils = {}

local Colors = {
    ['0'] = "Noir Métallisé",
    ['1'] = "Noir Graphite Métallisé",
    ['2'] = "Acier Noir Métallisé",
    ['3'] = "Argent Foncé Métallisé",
    ['4'] = "Argent Métallisé",
    ['5'] = "Argent Bleuté Métallisé",
    ['6'] = "Gris Acier Métallisé",
    ['7'] = "Argent Ombré Métallisé",
    ['8'] = "Argent Pierre Métallisé",
    ['9'] = "Argent Minuit Métallisé",
    ['10'] = "Gris Canon Métallisé",
    ['11'] = "Gris Anthracite Métallisé",
    ['12'] = "Noir Mat",
    ['13'] = "Gris Mat",
    ['14'] = "Gris Clair Mat",
    ['15'] = "Noir Utilitaire",
    ['16'] = "Noir Poly Utilitaire",
    ['17'] = "Argent Foncé Utilitaire",
    ['18'] = "Argent Utilitaire",
    ['19'] = "Gris Canon Utilitaire",
    ['20'] = "Argent Ombré Utilitaire",
    ['21'] = "Noir Usé",
    ['22'] = "Graphite Usé",
    ['23'] = "Gris Argent Usé",
    ['24'] = "Argent Usé",
    ['25'] = "Argent Bleuté Usé",
    ['26'] = "Argent Ombré Usé",
    ['27'] = "Rouge Métallisé",
    ['28'] = "Rouge Torino Métallisé",
    ['29'] = "Rouge Formule Métallisé",
    ['30'] = "Rouge Flamme Métallisé",
    ['31'] = "Rouge Gracieux Métallisé",
    ['32'] = "Rouge Grenat Métallisé",
    ['33'] = "Rouge Désert Métallisé",
    ['34'] = "Rouge Cabernet Métallisé",
    ['35'] = "Rouge Bonbon Métallisé",
    ['36'] = "Orange Aurore Métallisé",
    ['37'] = "Or Classique Métallisé",
    ['38'] = "Orange Métallisé",
    ['39'] = "Rouge Mat",
    ['40'] = "Rouge Foncé Mat",
    ['41'] = "Orange Mat",
    ['42'] = "Jaune Mat",
    ['43'] = "Rouge Utilitaire",
    ['44'] = "Rouge Vif Utilitaire",
    ['45'] = "Rouge Grenat Utilitaire",
    ['46'] = "Rouge Usé",
    ['47'] = "Rouge Doré Usé",
    ['48'] = "Rouge Foncé Usé",
    ['49'] = "Vert Foncé Métallisé",
    ['50'] = "Vert Course Métallisé",
    ['51'] = "Vert Mer Métallisé",
    ['52'] = "Vert Olive Métallisé",
    ['53'] = "Vert Métallisé",
    ['54'] = "Bleu Essence Métallisé",
    ['55'] = "Vert Citron Mat",
    ['56'] = "Vert Foncé Utilitaire",
    ['57'] = "Vert Utilitaire",
    ['58'] = "Vert Foncé Usé",
    ['59'] = "Vert Usé",
    ['60'] = "Vert Marin Usé",
    ['61'] = "Bleu Minuit Métallisé",
    ['62'] = "Bleu Foncé Métallisé",
    ['63'] = "Bleu Saxe Métallisé",
    ['64'] = "Bleu Métallisé",
    ['65'] = "Bleu Marin Métallisé",
    ['66'] = "Bleu Port Métallisé",
    ['67'] = "Bleu Diamant Métallisé",
    ['68'] = "Bleu Surf Métallisé",
    ['69'] = "Bleu Nautique Métallisé",
    ['70'] = "Bleu Vif Métallisé",
    ['71'] = "Bleu Violet Métallisé",
    ['72'] = "Bleu Spinnaker Métallisé",
    ['73'] = "Bleu Ultra Métallisé",
    ['74'] = "Bleu Vif Métallisé",
    ['75'] = "Bleu Foncé Utilitaire",
    ['76'] = "Bleu Minuit Utilitaire",
    ['77'] = "Bleu Utilitaire",
    ['78'] = "Bleu Écume Utilitaire",
    ['79'] = "Bleu Éclair Utilitaire",
    ['80'] = "Bleu Maui Poly Utilitaire",
    ['81'] = "Bleu Vif Utilitaire",
    ['82'] = "Bleu Foncé Mat",
    ['83'] = "Bleu Mat",
    ['84'] = "Bleu Minuit Mat",
    ['85'] = "Bleu Foncé Usé",
    ['86'] = "Bleu Usé",
    ['87'] = "Bleu Clair Usé",
    ['88'] = "Jaune Taxi Métallisé",
    ['89'] = "Jaune Course Métallisé",
    ['90'] = "Bronze Métallisé",
    ['91'] = "Jaune Canari Métallisé",
    ['92'] = "Jaune Citron Métallisé",
    ['93'] = "Champagne Métallisé",
    ['94'] = "Beige Pueblo Métallisé",
    ['95'] = "Ivoire Foncé Métallisé",
    ['96'] = "Marron Chocolat Métallisé",
    ['97'] = "Marron Doré Métallisé",
    ['98'] = "Marron Clair Métallisé",
    ['99'] = "Beige Paille Métallisé",
    ['100'] = "Marron Mousse Métallisé",
    ['101'] = "Marron Biston Métallisé",
    ['102'] = "Bois Hêtre Métallisé",
    ['103'] = "Bois Hêtre Foncé Métallisé",
    ['104'] = "Orange Chocolat Métallisé",
    ['105'] = "Sable Plage Métallisé",
    ['106'] = "Sable Décoloré Métallisé",
    ['107'] = "Crème Métallisé",
    ['108'] = "Marron Utilitaire",
    ['109'] = "Marron Moyen Utilitaire",
    ['110'] = "Marron Clair Utilitaire",
    ['111'] = "Blanc Métallisé",
    ['112'] = "Blanc Givré Métallisé",
    ['113'] = "Beige Miel Usé",
    ['114'] = "Marron Usé",
    ['115'] = "Marron Foncé Usé",
    ['116'] = "Beige Paille Usé",
    ['117'] = "Acier Brossé",
    ['118'] = "Acier Noir Brossé",
    ['119'] = "Aluminium Brossé",
    ['120'] = "Chrome",
    ['121'] = "Blanc Cassé Usé",
    ['122'] = "Blanc Cassé Utilitaire",
    ['123'] = "Orange Usé",
    ['124'] = "Orange Clair Usé",
    ['125'] = "Vert Securicor Métallisé",
    ['126'] = "Jaune Taxi Usé",
    ['127'] = "Bleu Police",
    ['128'] = "Vert Mat",
    ['129'] = "Marron Mat",
    ['130'] = "Orange Usé",
    ['131'] = "Blanc Mat",
    ['132'] = "Blanc Usé",
    ['133'] = "Vert Armée Olive Usé",
    ['134'] = "Blanc Pur",
    ['135'] = "Rose Vif",
    ['136'] = "Rose Saumon",
    ['137'] = "Rose Vermillon Métallisé",
    ['138'] = "Orange",
    ['139'] = "Vert",
    ['140'] = "Bleu",
    ['141'] = "Bleu Noir Métallisé",
    ['142'] = "Violet Noir Métallisé",
    ['143'] = "Rouge Noir Métallisé",
    ['144'] = "Vert Chasseur",
    ['145'] = "Violet Métallisé",
    ['146'] = "Bleu Foncé Métallisé",
    ['147'] = "Noir",
    ['148'] = "Violet Mat",
    ['149'] = "Violet Foncé Mat",
    ['150'] = "Rouge Lave Métallisé",
    ['151'] = "Vert Forêt Mat",
    ['152'] = "Olive Drab Mat",
    ['153'] = "Marron Désert Mat",
    ['154'] = "Beige Désert Mat",
    ['155'] = "Vert Feuillage Mat",
    ['156'] = "Couleur Alliage Par Défaut",
    ['157'] = "Bleu Epsilon",
    ['158'] = "Or Pur",
    ['159'] = "Or Brossé",
    ['160'] = "MP100"
}

local Classlist = {
    ["0"] = "Compactes",
    ["1"] = "Berlines",
    ["2"] = "SUVs",
    ["3"] = "Coupés",
    ["4"] = "Muscle",
    ["5"] = "Sport-Classique",
    ["6"] = "Sports",
    ["7"] = "Super",
    ["8"] = "Motos",
    ["9"] = "Tout-Terrain",
    ["10"] = "Industriels",
    ["11"] = "Utilitaires",
    ["12"] = "Fourgonnettes",
    ["13"] = "Vélos",
    ["14"] = "Bateaux",
    ["15"] = "Hélicoptères",
    ["16"] = "Avions",
    ["17"] = "Services",
    ["18"] = "Urgences",
    ["19"] = "Militaires",
    ["20"] = "Commerciaux",
    ["21"] = "Trains",
}

local weaponTable = {
    [584646201]   = "Catégorie 2: Pistolet AP",
    [453432689]   = "Catégorie 1: Pistolet",
    [3219281620]  = "Catégorie 1: Pistolet MK2",
    [1593441988]  = "Catégorie 1: Pistolet de Combat",
    [-1716589765] = "Catégorie 1: Pistolet Lourd",
    [-1076751822] = "Catégorie 1: Pistolet SNS",
    [-771403250]  = "Catégorie 2: Desert Eagle",
    [137902532]   = "Catégorie 2: Pistolet Vintage",
    [-598887786]  = "Catégorie 2: Pistolet de Précision",
    [-1045183535] = "Catégorie 2: Revolver",
    [911657153]   = "Taser",
    [324215364]   = "Catégorie 2: Micro-SMG",
    [-619010992]  = "Catégorie 2: Pistolet-Mitrailleur",
    [736523883]   = "Catégorie 2: SMG",
    [2024373456]  = "Catégorie 2: SMG MK2",
    [-270015777]  = "Catégorie 2: SMG d'Assaut",
    [171789620]   = "Catégorie 2: PDW de Combat",
    [-1660422300] = "Catégorie 4: Mitrailleuse de Combat",
    [3686625920]  = "Catégorie 4: Mitrailleuse de Combat MK2",
    [1627465347]  = "Catégorie 4: Gusenberg",
    [-1121678507] = "Catégorie 2: Mini SMG",
    [-1074790547] = "Catégorie 3: Fusil d'Assaut",
    [961495388]   = "Catégorie 3: Fusil d'Assaut MK2",
    [-2084633992] = "Catégorie 3: Carabine",
    [4208062921]  = "Catégorie 3: Carabine MK2",
    [-1357824103] = "Catégorie 3: Fusil Avancé",
    [-1063057011] = "Catégorie 3: Carabine Spéciale",
    [2132975508]  = "Catégorie 3: Fusil Bullpup",
    [1649403952]  = "Catégorie 3: Fusil Compact",
    [100416529]   = "Catégorie 4: Fusil de Sniper",
    [205991906]   = "Catégorie 4: Sniper Lourd",
    [177293209]   = "Catégorie 4: Sniper Lourd MK2",
    [-952879014]  = "Catégorie 4: Fusil de Précision",
    [487013001]   = "Catégorie 2: Fusil à Pompe",
    [2017895192]  = "Catégorie 2: Fusil à Canon Scié",
    [-1654528753] = "Catégorie 3: Fusil à Pompe Bullpup",
    [-494615257]  = "Catégorie 3: Fusil à Pompe d'Assaut",
    [-1466123874] = "Catégorie 3: Mousquet",
    [984333226]   = "Catégorie 3: Fusil à Pompe Lourd",
    [-275439685]  = "Catégorie 2: Fusil à Double Canon",
    [317205821]   = "Catégorie 2: Fusil à Pompe Auto",
    [-1568386805] = "Catégorie 5: Lance-Grenades",
    [-1312131151] = "Catégorie 5: Lance-Roquettes",
    [125959754]   = "Catégorie 5: Lance-Grenades Compact"
}

function utils.GetVehicleClassById(classId)
    return Classlist[tostring(classId)]
end

function utils.GetColor(color)
    return Colors[tostring(color)]
end

function utils.GetVehicleColor(vehicle)
    local vehicleColor1, vehicleColor2 = GetVehicleColours(vehicle)
    local color1 = Colors[tostring(vehicleColor1)]
    local color2 = Colors[tostring(vehicleColor2)]

    if color1 and color2 then return color2 .. " sur " .. color1 end

    if color1 then return color1 end

    if color2 then return color2 end

    
    return "Inconnue"
end

function utils.GetWeaponName()
    local currentWeapon = GetSelectedPedWeapon(cache.ped)
    return weaponTable[currentWeapon] or "Inconnue"
end

return utils