QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	judge = { label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Judge', payment = 100 } } },
	lawyer = { label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associate', payment = 50 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 50 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },
	
	unemployed = { 
		label = 'RSA', 
		defaultDuty = true, 
		offDutyPay = true, 
		grades = { 
			['0'] = { 
				name = 'Demandeur d\'emploie', 
				payment = 550 
			} 
		} 
	},
	maisonette10 = { 
		label = 'Maisonette 10', 
		defaultDuty = true, 
		offDutyPay = true, 
		grades = {
		['0'] = { name = 'DJ', payment = 1500 },
		['1'] = { name = 'Videur', payment = 1700 },
		['2'] = { name = 'Barman', payment = 1900 },
		['3'] = { name = 'Responsable Communication', payment = 2100 },
		['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
		['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
	},
},
	police_nationale = {
		label = 'Police Nationale',
		type = 'leo',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Gardien de la Paix', payment = 1500 },
			['1'] = { name = 'Lieutenant de Police', payment = 1700 },
			['2'] = { name = 'Capitaine de Police', payment = 1900 },
			['3'] = { name = 'Commandant de Police', payment = 2100 },
			['4'] = { name = 'Commissaire de Police', isboss = true, payment = 2500 },
		},
	},
	tabac = {
		label = 'Tabac',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Apprenti  ', payment = 1500 },
			['1'] = { name = 'Ouvrier  ', payment = 1700 },
			['2'] = { name = 'Préparateur  ', payment = 1900 },
			['3'] = { name = 'Responsable de Vente  ', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	mairie = {
		label = 'Mairie',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire ', payment = 1500 },
			['1'] = { name = 'Secrétaire ', payment = 1700 },
			['2'] = { name = 'Responsable voirie', payment = 1900 },
			['3'] = { name = 'Adjoint au Maire', payment = 2100 },
			['4'] = { name = 'Maire ', isboss = true, payment = 2500 },
		},
	},
	gendarmerie_nationale = {
		label = 'Gendarmerie Nationale',
		type = 'leo',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Gendarme (GND)', payment = 1300 },
			['1'] = { name = 'Gendarme (GNC)', payment = 1500 },
			['2'] = { name = 'Gendarme (MDC) ', payment = 1700 },
			['3'] = { name = 'Adjudant', payment = 1900 },
			['4'] = { name = 'Adjudant Chef', isboss = true, payment = 2100 },
			['5'] = { name = 'Major', isboss = true, payment = 2500 },
		},
	},
	samu_75 = {
		label = 'Samu 75',
		type = 'ems',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Interne ', payment = 1500 },
			['1'] = { name = 'Infirmier ', payment = 1700 },
			['2'] = { name = 'Médecin Urgentiste', payment = 1900 },
			['3'] = { name = 'Médecin-Chef', payment = 2100 },
			['4'] = { name = 'Directeur du SAMU 75', isboss = true, payment = 2500 },
		},
	},
	pompiers_de_paris = {
		label = 'Pompiers de Paris',
		type = 'ems',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Sapeur 2ᵉ Classe', payment = 1500 },
			['1'] = { name = 'Sapeur 1ʳᵉ Classe', payment = 1700 },
			['2'] = { name = 'Caporal-Chef', payment = 1900 },
			['3'] = { name = 'Adjudant-Chef', payment = 2100 },
			['4'] = { name = 'Colonel ', isboss = true, payment = 2500 },
		},
	},
	orpi = {
		label = 'Orpi',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Assistant Commercial', payment = 1500 },
			['1'] = { name = 'Agent Immobilier', payment = 1700 },
			['2'] = { name = 'Conseiller Immobilier', payment = 1900 },
			['3'] = { name = 'Responsable des Ventes', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire Taxi', payment = 1500 },
			['1'] = { name = 'Chauffeur Taxi', payment = 1700 },
			['2'] = { name = 'Chauffeur Expérimenté', payment = 1900 },
			['3'] = { name = 'Responsable de Flotte', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	concessionnaire = {
		label = 'Concessionnaire',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire ', payment = 1500 },
			['1'] = { name = 'Vendeur ', payment = 1700 },
			['2'] = { name = 'Conseiller Commercial', payment = 1900 },
			['3'] = { name = 'Responsable des Ventes', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	norauto = {
		label = 'Norauto',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Apprenti Mécanicien', payment = 1500 },
			['1'] = { name = 'Mécanicien ', payment = 1700 },
			['2'] = { name = 'Mécanicien Confirmé', payment = 1900 },
			['3'] = { name = 'Chef d\'Atelier', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	midas = {
		label = 'Midas',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Apprenti Mécanicien', payment = 1500 },
			['1'] = { name = 'Mécanicien ', payment = 1700 },
			['2'] = { name = 'Technicien Automobile', payment = 1900 },
			['3'] = { name = 'Chef d\'Atelier', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	vinci = {
		label = 'Vinci',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Ouvrier', payment = 1500 },
			['1'] = { name = 'Chef d\'Equipe', payment = 1700 },
			['2'] = { name = 'Conducteur de Travaux', payment = 1900 },
			['3'] = { name = 'Responsable de Chantier', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	otacos = {
		label = 'Otacos',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire Cuisine', payment = 1500 },
			['1'] = { name = 'Employé ', payment = 1700 },
			['2'] = { name = 'Chef de Cuisine', payment = 1900 },
			['3'] = { name = 'Responsable de Salle', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	kfc = {
		label = 'KFC',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire Cuisine', payment = 1500 },
			['1'] = { name = 'Employé Polyvalent', payment = 1700 },
			['2'] = { name = 'Chef de Cuisine', payment = 1900 },
			['3'] = { name = 'Manager ', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	pizza = {
		label = 'Pizza',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire Cuisine', payment = 1500 },
			['1'] = { name = 'Employé Polyvalent', payment = 1700 },
			['2'] = { name = 'Chef de Cuisine', payment = 1900 },
			['3'] = { name = 'Manager ', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	avocats_de_paris = {
		label = 'Avocats de Paris',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire en Droit', payment = 1500 },
			['1'] = { name = 'Avocat Junior', payment = 1700 },
			['2'] = { name = 'Avocat Confirmé', payment = 1900 },
			['3'] = { name = 'Associé du Cabinet ', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	vigneron = {
		label = 'Vigneron',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Ouvrier Viticole', payment = 1500 },
			['1'] = { name = 'Vigneron', payment = 1700 },
			['2'] = { name = 'Responsable de Production', payment = 1900 },
			['3'] = { name = 'Responsable des Ventes', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	brinks = {
		label = 'Brinks',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Agent de Sécurité', payment = 1500 },
			['1'] = { name = 'Convoyeur de Fonds', payment = 1700 },
			['2'] = { name = 'Chef d\'Équipe', payment = 1900 },
			['3'] = { name = 'Responsable Logistique', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	burgerking = {
		label = 'Burger King',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire Cuisine', payment = 1500 },
			['1'] = { name = 'Employé Polyvalent', payment = 1700 },
			['2'] = { name = 'Chef de Cuisine', payment = 1900 },
			['3'] = { name = 'Manager / Responsable', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	tf1 = {
		label = 'TF1',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire Journaliste', payment = 1500 },
			['1'] = { name = 'Journaliste', payment = 1700 },
			['2'] = { name = 'Rédacteur en Chef', payment = 1900 },
			['3'] = { name = 'Directeur des Programmes', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	dir = {
		label = 'Dir',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Agent Routier', payment = 1500 },
			['1'] = { name = 'Chef d\'Équipe', payment = 1700 },
			['2'] = { name = 'Responsable de Secteur', payment = 1900 },
			['3'] = { name = 'Directeur des Travaux', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	casino = {
		label = 'Casino',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Croupier', payment = 1500 },
			['1'] = { name = 'Agent de Sécurité', payment = 1700 },
			['2'] = { name = 'Responsable des Jeux', payment = 1900 },
			['3'] = { name = 'Directeur de Salle', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },
		},
	},
	xpo = {
		label = 'XPO Logistics',
		type = '',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Chauffeur-Livreur', payment = 1500 },
			['1'] = { name = 'Conducteur Poids-Lourd', payment = 1700 },
			['2'] = { name = 'Chef d\'Équipe Logistique', payment = 1900 },
			['3'] = { name = 'Responsable d\'Entrepôt', payment = 2100 },
			['4'] = { name = 'Co Gérant', isboss = true, payment = 2500 },
			['5'] = { name = 'Gérant', isboss = true, payment = 2500 },	
		},
	},
}


-- Jobs Creator integration (jobs_creator)
RegisterNetEvent("jobs_creator:injectJobs", function(jobs)
    QBShared.Jobs = jobs
end)
        