Config.IgnoreClasses = {
    [13] = true, -- Cycles
    [14] = true, -- Bateaux
    [15] = true, -- Hélicoptères
    [16] = true, -- Avions
    [21] = true, -- Trains
}

Config.WheelBones = {
    [0] = 'wheel_lf',
    [1] = 'wheel_rf',
    [2] = 'wheel_lm',
    [3] = 'wheel_rm',
    [4] = 'wheel_lr',
    [5] = 'wheel_rr',
    --[45] = '',
    --[46] = ''
}

Config.HornLabels = {
    [0] = 'Klaxon de Camion',
    [1] = 'Klaxon de Police',
    [2] = 'Klaxon de Clown',
    [3] = 'Klaxon Musical 1',
    [4] = 'Klaxon Musical 2',
    [5] = 'Klaxon Musical 3',
    [6] = 'Klaxon Musical 4',
    [7] = 'Klaxon Musical 5',
    [8] = 'Trombone Triste',
    [9] = 'Klaxon Classique 1',
    [10] = 'Klaxon Classique 2',
    [11] = 'Klaxon Classique 3',
    [12] = 'Klaxon Classique 4',
    [13] = 'Klaxon Classique 5',
    [14] = 'Klaxon Classique 6',
    [15] = 'Klaxon Classique 7',
    [16] = 'Gamme - Do',
    [17] = 'Gamme - Ré',
    [18] = 'Gamme - Mi',
    [19] = 'Gamme - Fa',
    [20] = 'Gamme - Sol',
    [21] = 'Gamme - La',
    [22] = 'Gamme - Si',
    [23] = 'Gamme - Do',
    [24] = 'Klaxon Jazz 1',
    [25] = 'Klaxon Jazz 2',
    [26] = 'Klaxon Jazz 3',
    [27] = 'Klaxon Jazz en Boucle',
    [28] = 'Star Spangled Banner 1',
    [29] = 'Star Spangled Banner 2',
    [30] = 'Star Spangled Banner 3',
    [31] = 'Star Spangled Banner 4',
    [32] = 'Klaxon Classique 8 en Boucle',
    [33] = 'Klaxon Classique 9 en Boucle',
    [34] = 'Klaxon Classique 10 en Boucle',
    [35] = 'Klaxon Classique 8',
    [36] = 'Klaxon Classique 9',
    [37] = 'Klaxon Classique 10',
    [38] = 'Funéraire en Boucle',
    [39] = 'Funéraire',
    [40] = 'Effrayant en Boucle',
    [41] = 'Effrayant',
    [42] = 'San Andreas en Boucle',
    [43] = 'San Andreas',
    [44] = 'Liberty City en Boucle',
    [45] = 'Liberty City',
    [46] = 'Festif 1 en Boucle',
    [47] = 'Festif 1',
    [48] = 'Festif 2 en Boucle',
    [49] = 'Festif 2',
    [50] = 'Festif 3 en Boucle',
    [51] = 'Festif 3'
}

-- https://docs.fivem.net/natives/?_0xB3ED1BFB4BE636DC
Config.WheelCategories = {
    { label = 'Sport',              id = 0 },
    { label = 'Muscle',             id = 1 },
    { label = 'Lowrider',           id = 2 },
    { label = 'SUV',                id = 3 },
    { label = 'Tout-Terrain',       id = 4 },
    { label = 'Tuning',             id = 5 },
    { label = 'Moto',               id = 6 },
    { label = 'Haut de Gamme',      id = 7 },
    { label = 'Benny\'s Originaux', id = 8 },
    { label = 'Benny\'s Sur Mesure', id = 9 },
    { label = 'Roue Ouverte',       id = 10 },
    { label = 'Rue',                id = 11 },
    { label = 'Piste',              id = 12 },
}

-- https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD
Config.InteriorCategories = {
    { label = 'Arceau',           id = 5 },
    { label = 'Klaxons',          id = 14 },
    { label = 'Caisson de Basse', id = 19 },
    { label = 'Tableau de Bord',  id = 29 },
    { label = 'Cadran',           id = 30 },
    { label = 'Haut-Parleur de Porte', id = 31 },
    { label = 'Sièges',           id = 32 },
    { label = 'Volant',           id = 33 },
    { label = 'Levier de Vitesse', id = 34 },
    { label = 'Plaque',           id = 35 },
    { label = 'Haut-Parleur',     id = 36 },
}

-- https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD
Config.ExteriorCategories = {
    { label = 'Aileron',        id = 0 },
    { label = 'Pare-Chocs Avant', id = 1 },
    { label = 'Pare-Chocs Arrière', id = 2 },
    { label = 'Bas de Caisse',   id = 3 },
    { label = 'Échappement',    id = 4 },
    { label = 'Calandre',       id = 6 },
    { label = 'Capot',          id = 7 },
    { label = 'Aile Gauche',    id = 8 },
    { label = 'Aile Droite',    id = 9 },
    { label = 'Toit',           id = 10 },
    { label = 'Suspension Hydraulique', id = 21 },
    { label = 'Phares',         id = 22 },
    { label = 'Fumée de Pneu',  id = 20 },
    { label = 'Roues Arrière',  id = 24 },
    { label = 'Support de Plaque', id = 25 },
    { label = 'Plaques Personnalisées', id = 26 },
    { label = 'Garniture A',    id = 27 },
    { label = 'Ornements',      id = 28 },
    { label = 'Coffre',         id = 37 },
    { label = 'Hydraulique',    id = 38 },
    { label = 'Bloc Moteur',    id = 39 },
    { label = 'Filtre à Air',   id = 40 },
    { label = 'Jambe de Force', id = 41 },
    { label = 'Cache d\'Arche', id = 42 },
    { label = 'Antenne',        id = 43 },
    { label = 'Garniture B',    id = 44 },
    { label = 'Réservoir de Carburant', id = 45 },
    { label = 'Vitre',          id = 46 },
    { label = 'Porte',          id = 47 },
    { label = 'Livrée',         id = 48 },
    { label = 'Barre Lumineuse', id = 49 },
    { label = 'Peinture',       id = 50 }
}

-- https://docs.fivem.net/natives/?_0x3DFF319A831E0CDB
Config.Xenon = {
    { label = 'Défaut',        id = -1 },
    { label = 'Blanc',         id = 0 },
    { label = 'Bleu',          id = 1 },
    { label = 'Bleu Électrique', id = 2 },
    { label = 'Vert Menthe',   id = 3 },
    { label = 'Vert Lime',     id = 4 },
    { label = 'Jaune',         id = 5 },
    { label = 'Doré',          id = 6 },
    { label = 'Orange',        id = 7 },
    { label = 'Rouge',         id = 8 },
    { label = 'Rose Poney',    id = 9 },
    { label = 'Rose Vif',      id = 10 },
    { label = 'Violet',        id = 11 },
    { label = 'Lumière Noire', id = 12 },
}

-- https://docs.fivem.net/natives/?_0x57C51E6BAD752696
Config.WindowTints = {
    { label = 'Aucun',         id = 0 },
    { label = 'Noir Pur',      id = 1 },
    { label = 'Fumé Foncé',    id = 2 },
    { label = 'Fumé Léger',    id = 3 },
    { label = 'Standard',      id = 4 },
    { label = 'Limousine',     id = 5 },
    { label = 'Vert',          id = 6 },
}

-- https://docs.fivem.net/natives/?_0x9088EB5A43FFB0A1
Config.PlateIndexes = {
    { label = 'Bleu sur Blanc 1', id = 0 },
    { label = 'Jaune sur Noir',   id = 1 },
    { label = 'Jaune sur Bleu',   id = 2 },
    { label = 'Bleu sur Blanc 2', id = 3 },
    { label = 'Bleu sur Blanc 3', id = 4 },
    { label = 'Yankton',          id = 5 },
    { label = 'Ecola',            id = 6 },
    { label = 'Las Venturas',     id = 7 },
    { label = 'Liberty City',     id = 8 },
    { label = 'LS Car Meet',      id = 9 },
    { label = 'Panic',            id = 10 },
    { label = 'Pounders',         id = 11 },
    { label = 'Sprunk',           id = 12 },
}

-- https://docs.fivem.net/natives/?_0x2AA720E4287BF269
Config.Neon = {
    { label = 'Gauche',  id = 0 },
    { label = 'Droite', id = 1 },
    { label = 'Avant', id = 2 },
    { label = 'Arrière',  id = 3 },
}

-- https://docs.fivem.net/natives/?_0x8E0A582209A62695
Config.NeonColors = {
    { label = 'Blanc',           r = 222, g = 222, b = 255 },
    { label = 'Bleu',            r = 2,   g = 21,  b = 255 },
    { label = 'Bleu Électrique', r = 3,   g = 83,  b = 255 },
    { label = 'Vert Menthe',     r = 0,   g = 255, b = 140 },
    { label = 'Vert Lime',       r = 94,  g = 255, b = 1 },
    { label = 'Jaune',           r = 255, g = 255, b = 0 },
    { label = 'Doré',            r = 255, g = 150, b = 0 },
    { label = 'Orange',          r = 255, g = 62,  b = 0 },
    { label = 'Rouge',           r = 255, g = 1,   b = 1 },
    { label = 'Rose Poney',      r = 255, g = 50,  b = 100 },
    { label = 'Rose Vif',        r = 255, g = 5,   b = 190 },
    { label = 'Violet',          r = 35,  g = 1,   b = 255 },
    { label = 'Lumière Noire',   r = 15,  g = 3,   b = 255 },
}

-- https://docs.fivem.net/natives/?_0xB5BA80F839791C0F
Config.TyreSmoke = {
    { label = 'Fumée Blanche',  r = 254, g = 254, b = 254 },
    { label = 'Fumée Noire',    r = 1,   g = 1,   b = 1 },
    { label = 'Fumée Bleue',    r = 0,   g = 150, b = 255 },
    { label = 'Fumée Jaune',    r = 255, g = 255, b = 50 },
    { label = 'Fumée Orange',   r = 255, g = 153, b = 51 },
    { label = 'Fumée Rouge',    r = 255, g = 10,  b = 10 },
    { label = 'Fumée Verte',    r = 10,  g = 255, b = 10 },
    { label = 'Fumée Violette', r = 153, g = 10,  b = 153 },
    { label = 'Fumée Rose',     r = 255, g = 102, b = 178 },
    { label = 'Fumée Grise',    r = 128, g = 128, b = 128 }
}

Config.Paints = {

    Metallic = {
        { label = 'Noir Métallisé',                 id = 0,   hex = '0d1116' },
        { label = 'Noir Graphite Métallisé',        id = 1,   hex = '1c1d21' },
        { label = 'Noir Acier Métallisé',           id = 2,   hex = '32383d' },
        { label = 'Argent Foncé Métallisé',         id = 3,   hex = '454b4f' },
        { label = 'Argent Métallisé',               id = 4,   hex = '999da0' },
        { label = 'Argent Bleuté Métallisé',        id = 5,   hex = 'c2c4c6' },
        { label = 'Gris Acier Métallisé',           id = 6,   hex = '979a97' },
        { label = 'Argent Ombré Métallisé',         id = 7,   hex = '637380' },
        { label = 'Argent Pierre Métallisé',        id = 8,   hex = '63625c' },
        { label = 'Argent Minuit Métallisé',        id = 9,   hex = '3c3f47' },
        { label = 'Gun Metal Métallisé',            id = 10,  hex = '444e54' },
        { label = 'Gris Anthracite Métallisé',      id = 11,  hex = '1d2129' },
        { label = 'Rouge Métallisé',                id = 27,  hex = 'c00e1a' },
        { label = 'Rouge Torino Métallisé',         id = 28,  hex = 'da1918' },
        { label = 'Rouge Formule Métallisé',        id = 29,  hex = 'b6111b' },
        { label = 'Rouge Flamme Métallisé',         id = 30,  hex = 'a51e23' },
        { label = 'Rouge Gracieux Métallisé',       id = 31,  hex = '7b1a22' },
        { label = 'Rouge Grenat Métallisé',         id = 32,  hex = '8e1b1f' },
        { label = 'Rouge Désert Métallisé',         id = 33,  hex = '6f1818' },
        { label = 'Rouge Cabernet Métallisé',       id = 34,  hex = '49111d' },
        { label = 'Rouge Bonbon Métallisé',         id = 35,  hex = 'b60f25' },
        { label = 'Orange Lever de Soleil Métallisé', id = 36,  hex = 'd44a17' },
        { label = 'Or Classique Métallisé',         id = 37,  hex = 'c2944f' },
        { label = 'Orange Métallisé',               id = 38,  hex = 'f78616' },
        { label = 'Vert Foncé Métallisé',           id = 49,  hex = '132428' },
        { label = 'Vert Course Métallisé',          id = 50,  hex = '122e2b' },
        { label = 'Vert Mer Métallisé',             id = 51,  hex = '12383c' },
        { label = 'Vert Olive Métallisé',           id = 52,  hex = '31423f' },
        { label = 'Vert Métallisé',                 id = 53,  hex = '155c2d' },
        { label = 'Bleu-Vert Essence Métallisé',    id = 54,  hex = '1b6770' },
        { label = 'Bleu Minuit Métallisé',          id = 61,  hex = '222e46' },
        { label = 'Bleu Foncé Métallisé',           id = 62,  hex = '233155' },
        { label = 'Bleu Saxony Métallisé',          id = 63,  hex = '304c7e' },
        { label = 'Bleu Métallisé',                 id = 64,  hex = '47578f' },
        { label = 'Bleu Marin Métallisé',           id = 65,  hex = '637ba7' },
        { label = 'Bleu Port Métallisé',            id = 66,  hex = '394762' },
        { label = 'Bleu Diamant Métallisé',         id = 67,  hex = 'd6e7f1' },
        { label = 'Bleu Surf Métallisé',            id = 68,  hex = '76afbe' },
        { label = 'Bleu Nautique Métallisé',        id = 69,  hex = '345e72' },
        { label = 'Bleu Vif Métallisé',             id = 70,  hex = '0b9cf1' },
        { label = 'Bleu Violet Métallisé',          id = 71,  hex = '2f2d52' },
        { label = 'Bleu Spinnaker Métallisé',       id = 72,  hex = '282c4d' },
        { label = 'Bleu Ultra Métallisé',           id = 73,  hex = '2354a1' },
        { label = 'Bleu Vif Métallisé',             id = 74,  hex = '6ea3c6' },
        { label = 'Jaune Taxi Métallisé',           id = 88,  hex = 'ffcf20' },
        { label = 'Jaune Course Métallisé',         id = 89,  hex = 'fbe212' },
        { label = 'Bronze Métallisé',               id = 90,  hex = '916532' },
        { label = 'Jaune Oiseau Métallisé',         id = 91,  hex = 'e0e13d' },
        { label = 'Lime Métallisé',                 id = 92,  hex = '98d223' },
        { label = 'Champagne Métallisé',            id = 93,  hex = '9b8c78' },
        { label = 'Beige Pueblo Métallisé',         id = 94,  hex = '503218' },
        { label = 'Ivoire Foncé Métallisé',         id = 95,  hex = '473f2b' },
        { label = 'Brun Chocolat Métallisé',        id = 96,  hex = '221b19' },
        { label = 'Brun Doré Métallisé',            id = 97,  hex = '653f23' },
        { label = 'Brun Clair Métallisé',           id = 98,  hex = '775c3e' },
        { label = 'Beige Paille Métallisé',         id = 99,  hex = 'ac9975' },
        { label = 'Brun Mousse Métallisé',          id = 100, hex = '6c6b4b' },
        { label = 'Brun Biston Métallisé',          id = 101, hex = '402e2b' },
        { label = 'Bois de Hêtre Métallisé',        id = 102, hex = 'a4965f' },
        { label = 'Bois de Hêtre Foncé Métallisé',  id = 103, hex = '46231a' },
        { label = 'Orange Chocolat Métallisé',      id = 104, hex = '752b19' },
        { label = 'Sable de Plage Métallisé',       id = 105, hex = 'bfae7b' },
        { label = 'Sable Décoloré Métallisé',       id = 106, hex = 'dfd5b2' },
        { label = 'Crème Métallisé',                id = 107, hex = 'f7edd5' },
        { label = 'Blanc Métallisé',                id = 111, hex = 'fffff6' },
        { label = 'Blanc Givré Métallisé',          id = 112, hex = 'eaeaea' },
        { label = 'Vert Securicor Métallisé',       id = 125, hex = '83c566' },
        { label = 'Rose Vermillon Métallisé',       id = 137, hex = 'df5891' },
        { label = 'Noir Bleuté Métallisé',          id = 141, hex = '0a0c17' },
        { label = 'Noir Violet Métallisé',          id = 142, hex = '0c0d18' },
        { label = 'Noir Rouge Métallisé',           id = 143, hex = '0e0d14' },
        { label = 'Violet Métallisé',               id = 145, hex = '621276' },
        { label = 'Bleu Très Foncé Métallisé',      id = 146, hex = '0b1421' },
        { label = 'Rouge Lave Métallisé',           id = 150, hex = 'bc1917' },
    },

    Matte = {
        { label = 'Noir Mat',         id = 12,  hex = '13181f' },
        { label = 'Gris Mat',          id = 13,  hex = '26282a' },
        { label = 'Gris Clair Mat',    id = 14,  hex = '515554' },
        { label = 'Rouge Mat',           id = 39,  hex = 'cf1f21' },
        { label = 'Rouge Foncé Mat',      id = 40,  hex = '732021' },
        { label = 'Orange Mat',        id = 41,  hex = 'f27d20' },
        { label = 'Jaune Mat',        id = 42,  hex = 'ffc91f' },
        { label = 'Vert Lime Mat',    id = 55,  hex = '66b81f' },
        { label = 'Bleu Foncé Mat',     id = 82,  hex = '1f2852' },
        { label = 'Bleu Mat',          id = 83,  hex = '253aa7' },
        { label = 'Bleu Minuit Mat', id = 84,  hex = '1c3551' },
        { label = 'Vert Mat',         id = 128, hex = '4e6443' },
        { label = 'Brun Mat',         id = 129, hex = 'bcac8f' },
        { label = 'Blanc Mat',         id = 131, hex = 'fcf9f1' },
        { label = 'Violet Mat',        id = 148, hex = '6b1f7b' },
        { label = 'Violet Foncé Mat',   id = 149, hex = '1e1d22' },
        { label = 'Vert Forêt Mat',  id = 151, hex = '2d362a' },
        { label = 'Olive Kaki Mat',    id = 152, hex = '696748' },
        { label = 'Brun Désert Mat',  id = 153, hex = '7a6c55' },
        { label = 'Beige Désert Mat',    id = 154, hex = 'c3b492' },
        { label = 'Vert Feuillage Mat', id = 155, hex = '5a6352' },
    },

    Util = {
        { label = 'Noir Utilitaire',          id = 15,  hex = '151921' },
        { label = 'Noir Poly Utilitaire',     id = 16,  hex = '1e2429' },
        { label = 'Argent Foncé Utilitaire',    id = 17,  hex = '333a3c' },
        { label = 'Argent Utilitaire',         id = 18,  hex = '8c9095' },
        { label = 'Gun Metal Utilitaire',      id = 19,  hex = '39434d' },
        { label = 'Argent Ombré Utilitaire',  id = 20,  hex = '506272' },
        { label = 'Rouge Utilitaire',            id = 43,  hex = '9c1016' },
        { label = 'Rouge Vif Utilitaire',     id = 44,  hex = 'de0f18' },
        { label = 'Rouge Grenat Utilitaire',     id = 45,  hex = '8f1e17' },
        { label = 'Vert Foncé Utilitaire',     id = 56,  hex = '22383e' },
        { label = 'Vert Utilitaire',          id = 57,  hex = '1d5a3f' },
        { label = 'Bleu Foncé Utilitaire',      id = 75,  hex = '112552' },
        { label = 'Bleu Minuit Utilitaire',  id = 76,  hex = '1b203e' },
        { label = 'Bleu Utilitaire',           id = 77,  hex = '275190' },
        { label = 'Bleu Écume de Mer Utilitaire',  id = 78,  hex = '608592' },
        { label = 'Bleu Éclair Utilitaire', id = 79,  hex = '2446a8' },
        { label = 'Bleu Maui Poly Utilitaire', id = 80,  hex = '4271e1' },
        { label = 'Bleu Vif Utilitaire',    id = 81,  hex = '3b39e0' },
        { label = 'Brun Utilitaire',          id = 108, hex = '3a2a1b' },
        { label = 'Brun Moyen Utilitaire',   id = 109, hex = '785f33' },
        { label = 'Brun Clair Utilitaire',    id = 110, hex = 'b5a079' },
        { label = 'Blanc Cassé Utilitaire',      id = 122, hex = 'dfddd0' },
    },

    Worn = {
        { label = 'Noir Usé',            id = 21,  hex = '1e232f' },
        { label = 'Graphite Usé',        id = 22,  hex = '363a3f' },
        { label = 'Gris Argenté Usé',    id = 23,  hex = 'a0a199' },
        { label = 'Argent Usé',          id = 24,  hex = 'd3d3d3' },
        { label = 'Argent Bleu Usé',     id = 25,  hex = 'b7bfca' },
        { label = 'Argent Ombre Usé',    id = 26,  hex = '778794' },
        { label = 'Rouge Usé',           id = 46,  hex = 'a94744' },
        { label = 'Rouge Doré Usé',      id = 47,  hex = 'b16c51' },
        { label = 'Rouge Foncé Usé',     id = 48,  hex = '371c25' },
        { label = 'Vert Foncé Usé',      id = 58,  hex = '2d423f' },
        { label = 'Vert Usé',            id = 59,  hex = '45594b' },
        { label = 'Vert Océan Usé',      id = 60,  hex = '65867f' },
        { label = 'Bleu Foncé Usé',      id = 85,  hex = '4c5f81' },
        { label = 'Bleu Usé',            id = 86,  hex = '58688e' },
        { label = 'Bleu Clair Usé',      id = 87,  hex = '74b5d8' },
        { label = 'Beige Miel Usé',      id = 113, hex = 'b0ab94' },
        { label = 'Marron Usé',          id = 114, hex = '453831' },
        { label = 'Marron Foncé Usé',    id = 115, hex = '2a282b' },
        { label = 'Beige Paille Usé',    id = 116, hex = '726c57' },
        { label = 'Blanc Cassé Usé',     id = 121, hex = 'eae6de' },
        { label = 'Orange Usé',          id = 123, hex = 'f2ad2e' },
        { label = 'Orange Clair Usé',    id = 124, hex = 'f9a458' },
        { label = 'Jaune Taxi Usé',      id = 126, hex = 'f1cc40' },
        { label = 'Orange Usé',          id = 130, hex = 'f8b658' },
        { label = 'Blanc Usé',           id = 132, hex = 'fffffb' },
        { label = 'Vert Armée Usé',      id = 133, hex = '81844c' },
    },

    Misc = {
        { label = 'Acier Brossé',        id = 117, hex = '6a747c' },
        { label = 'Acier Noir Brossé',   id = 118, hex = '354158' },
        { label = 'Aluminium Brossé',    id = 119, hex = '9ba0a8' },
        { label = 'Chrome',              id = 120, hex = '5870a1' },
        { label = 'Bleu Voiture de Police', id = 127, hex = '4cc3da' },
        { label = 'Blanc Pur',           id = 134, hex = 'ffffff' },
        { label = 'Rose Flashy',         id = 135, hex = 'f21f99' },
        { label = 'Rose Saumon',         id = 136, hex = 'fdd6cd' },
        { label = 'Orange',              id = 138, hex = 'f6ae20' },
        { label = 'Vert',                id = 139, hex = 'b0ee6e' },
        { label = 'Bleu',                id = 140, hex = '08e9fa' },
        { label = 'Vert Chasseur',       id = 144, hex = '9f9e8a' },
        { label = 'Noir Atelier Mod',    id = 147, hex = '11141a' },
        { label = 'Alliage',             id = 156, hex = '81827f' },
        { label = 'Bleu Epsilon',        id = 157, hex = 'afd6e4' },
        { label = 'Or Pur',              id = 158, hex = '7a6440' },
        { label = 'Or Brossé',           id = 159, hex = '7f6a48' }
    },

    Chameleon = {
        { label = 'Rouge Anodisé',           id = 161, hex = 'CF1020' },
        { label = 'Vin Anodisé',             id = 162, hex = '5E1224' },
        { label = 'Violet Anodisé',          id = 163, hex = '800080' },
        { label = 'Bleu Anodisé',            id = 164, hex = '0000FF' },
        { label = 'Vert Anodisé',            id = 165, hex = '008000' },
        { label = 'Vert Citron Anodisé',     id = 166, hex = 'AFFF00' },
        { label = 'Cuivre Anodisé',          id = 167, hex = 'B87333' },
        { label = 'Bronze Anodisé',          id = 168, hex = 'CD7F32' },
        { label = 'Champagne Anodisé',       id = 169, hex = 'F7E7CE' },
        { label = 'Or Anodisé',              id = 170, hex = 'FFD700' },
        { label = 'Flip Vert Bleu',          id = 171, hex = '1164B4' },
        { label = 'Flip Vert Rouge',         id = 172, hex = 'B43104' },
        { label = 'Flip Vert Marron',        id = 173, hex = '735C12' },
        { label = 'Flip Vert Turquoise',     id = 174, hex = '43C6DB' },
        { label = 'Flip Vert Violet',        id = 175, hex = '9D00FF' },
        { label = 'Flip Bleu Rose',          id = 180, hex = '4C2882' },
        { label = 'Flip Bleu Vert',          id = 181, hex = '138808' },
        { label = 'Flip Violet Rouge',       id = 182, hex = '9B111E' },
        { label = 'Flip Magenta Orange',     id = 189, hex = 'FF5F1F' },
        { label = 'Flip Rouge Orange',       id = 190, hex = 'FF4500' },
        { label = 'Perle Verte',             id = 207, hex = '00A550' },
        { label = 'Perle Bleue',             id = 208, hex = '0000FF' },
        { label = 'Perle Crème',             id = 209, hex = 'FFFDD0' },
        { label = 'Prismatique Blanc',       id = 210, hex = 'FFFFFF' },
        { label = 'Prismatique Noir',        id = 217, hex = '000000' },
        { label = 'Arc-en-ciel Noir',        id = 219, hex = '000000' },
        { label = 'Coucher de Soleil',       id = 233, hex = 'FFD700' },
        { label = 'C\'est Noël',              id = 237, hex = 'FF0000' },
        { label = 'Température',             id = 238, hex = 'FFA07A' },
        { label = 'Perle Jaune Orange',      id = 239, hex = 'FFAE42' },
        { label = 'Perle Rose Bleue',        id = 240, hex = 'D8BFD8' },
        { label = 'Perle Vert Bleu',         id = 241, hex = '3CB371' },
        { label = 'Perle Turquoise Noir',    id = 242, hex = '00CED1' }
    },
}

if Config.ColorFavorites then
    Config.Paints.Favorites = { -- ajoutez vos couleurs personnalisées préférées ici avec leur code hexadécimal
        { label = 'Nom de ma peinture personnalisée !', hex = '' }
    }
end