QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civil', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Indépendant', payment = 10 } } },
	bus = { label = 'Chauffeur de Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 50 } } },
	judge = { label = 'Juge', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Juge', payment = 100 } } },
	lawyer = { label = 'Cabinet d\'Avocats', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associé', payment = 50 } } },
	reporter = { label = 'Journaliste', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journaliste', payment = 50 } } },
	trucker = { label = 'Routier', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 50 } } },
	tow = { label = 'Dépanneur', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 50 } } },
	garbage = { label = 'Éboueur', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collecteur', payment = 50 } } },
	vineyard = { label = 'Viticulteur', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Cueilleur', payment = 50 } } },
	hotdog = { label = 'Vendeur de Hot-dog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Vendeur', payment = 50 } } },

	gouv = {
		label = 'Gouvernement',
		type = 'leo',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Assistant', payment = 100 },
			['1'] = { name = 'Securite', payment = 150 },
			['2'] = { name = 'Vice Gouverneur', payment = 175 },
			['3'] = { name = 'Gouverneur', isboss = true, payment = 200 },
			
		},
	},
	police = {
		label = 'Los Santos Police Department',
		type = 'leo',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Rookie', payment = 75 },
            ['1'] = { name = 'Officier I', payment = 100 },                              			                                            
			['2'] = { name = 'Officier II', payment = 125 },
			['3'] = { name = 'Officier III', payment = 150 },
			['4'] = { name = 'Senior Leader Officier', payment = 175 },
            ['5'] = { name = 'Sergent I', payment = 200 },            
            ['6'] = { name = 'Sergent II', payment = 250 },            
            ['7'] = { name = 'Lieutenant I', payment = 275 },
            ['8'] = { name = 'Lieutenant II', payment = 300 },
            ['9'] = { name = 'Capitaine', payment = 375 },
            ['10'] = { name = 'Commandant', payment = 400, isboss = true },   
		},
	},
	bcso = {
		label = 'Blaine County Sheriff Office',
		type = 'leo',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Junior', payment = 75 },
            ['1'] = { name = 'Deputy I', payment = 100 },
            ['2'] = { name = 'Deputy II', payment = 125 },
            ['3'] = { name = 'Deputy III', payment = 150 },
            ['4'] = { name = 'Senior Deputy', payment = 175 },
            ['5'] = { name = 'Brigadier I', payment = 200 },
            ['6'] = { name = 'Brigadier II', payment = 250 },
            ['7'] = { name = 'Corporal I', payment = 275 },
            ['8'] = { name = 'Corporal II', payment = 300 },
            ['9'] = { name = 'Sherif Adjoint', payment = 375 },
            ['10'] = { name = 'Sheriff', payment = 400, isboss = true },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Stagiaire', payment = 75 },
			['1'] = { name = 'Ambulancier', payment = 100 },
			['2'] = { name = 'Ambulancier Confirmé', payment = 125 },
			['3'] = { name = 'Infirmier', payment = 150 },
			['4'] = { name = 'Infirmier Chef', payment = 175 },
			['5'] = { name = 'Médecin', payment = 200 },
			['6'] = { name = 'Médecin Chef', payment = 250 },
			['7'] = { name = 'Chirurgien', payment = 275 },
			['8'] = { name = 'Chef de Service', payment = 300 },
			['9'] = { name = 'Directeur Adjoint', payment = 375 },
			['10'] = { name = 'Directeur', payment = 400, isboss = true },
		},
	},
	realestate = {
		label = 'Immobilier',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Vendeur Particulier', payment = 75 },
			['2'] = { name = 'Vendeur Professionnel', payment = 100 },
			['3'] = { name = 'Courtier', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Chauffeur', payment = 75 },
			['2'] = { name = 'Chauffeur Événementiel', payment = 100 },
			['3'] = { name = 'Commercial', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Concessionnaire Automobile',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Vendeur Showroom', payment = 75 },
			['2'] = { name = 'Vendeur Professionnel', payment = 100 },
			['3'] = { name = 'Financier', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Expérimenté', payment = 100 },
			['3'] = { name = 'Avancé', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Expérimenté', payment = 100 },
			['3'] = { name = 'Avancé', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Expérimenté', payment = 100 },
			['3'] = { name = 'Avancé', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Expérimenté', payment = 100 },
			['3'] = { name = 'Avancé', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Expérimenté', payment = 100 },
			['3'] = { name = 'Avancé', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
}
