----------------------------------
--<!>-- BOII | DEVELOPMENT --<!>--
----------------------------------

-- Language settings
Language = {
    Targeting = {
        ['playercropicon'] = 'fa-solid fa-wheat-awn', -- Icône des cultures du joueur
        ['playercroplabel'] = 'Vérifier la Culture', -- Label des cultures du joueur
    },
    XP = {
        ['commandtext'] = 'Affiche votre expérience actuelle en agriculture.', -- Texte de la commande
        ['xpnotif'] = 'Agriculture:', -- Notification
    },
    Farming = {
        Trees = {
            ['pickapplexp'] = 'Vous avez cueilli des '..Config.Farming.Trees.Apple.Return.label..'s et gagné un peu d\'expérience !', -- Notification
            ['pickapplenoxp'] = 'Vous avez cueilli des '..Config.Farming.Trees.Apple.Return.label..'s !', -- Notification
            ['pickorangexp'] = 'Vous avez cueilli des '..Config.Farming.Trees.Orange.Return.label..'s et gagné un peu d\'expérience !', -- Notification
            ['pickorangenoxp'] = 'Vous avez cueilli des '..Config.Farming.Trees.Orange.Return.label..'s !', -- Notification
            ['picklemonxp'] = 'Vous avez cueilli des '..Config.Farming.Trees.Lemon.Return.label..'s et gagné un peu d\'expérience !', -- Notification
            ['picklemonnoxp'] = 'Vous avez cueilli des '..Config.Farming.Trees.Lemon.Return.label..'s !', -- Notification
            ['picklimexp'] = 'Vous avez cueilli des '..Config.Farming.Trees.Lime.Return.label..'s et gagné un peu d\'expérience !', -- Notification
            ['picklimenoxp'] = 'Vous avez cueilli des '..Config.Farming.Trees.Lime.Return.label..'s !', -- Notification
            ['picktreefailxp'] = 'Le fruit n\'est pas encore assez mûr.. Vous avez perdu de l\'expérience pour avoir perdu du temps..', -- Notification
            ['picktreefailnoxp'] = 'Le fruit n\'est pas encore assez mûr..', -- Notification
            ['pickapple'] = 'Cueillette de Pommes..', -- Barre de progression
            ['pickorange'] = 'Cueillette d\'Oranges..', -- Barre de progression
            ['picklemon'] = 'Cueillette de Citrons..', -- Barre de progression
            ['picklime'] = 'Cueillette de Limes..', -- Barre de progression
        },
        Animals = {
            ['nopail'] = 'Vous ne pouvez pas traire les vaches sans un '..Config.Farming.Animals.Cow.Required.label..'..', -- Notification
            ['alreadypetdog'] = 'Vous avez déjà caressé un chien, revenez dans ('..Config.Farming.Animals.Dog.Cooldown..') minutes..', -- Notification
            ['alreadypetpig'] = 'Vous avez déjà caressé un cochon, revenez dans ('..Config.Farming.Animals.Pig.Cooldown..') minutes..', -- Notification
            ['alreadymilking'] = 'Vous êtes déjà en train de traire une vache..', -- Notification
            ['collecteggxp'] = 'Vous avez collecté des '..Config.Farming.Animals.Chicken.Return.label..'s et gagné un peu d\'expérience !', -- Notification
            ['collecteggnoxp'] = 'Vous avez collecté des '..Config.Farming.Animals.Chicken.Return.label..'s !', -- Notification
            ['collectmilkxp'] = 'Vous avez collecté du '..Config.Farming.Animals.Cow.Return.label..' et gagné un peu d\'expérience !', -- Notification
            ['collectmilknoxp'] = 'Vous avez collecté du '..Config.Farming.Animals.Cow.Return.label..' !', -- Notification
            ['collectanimalfailxp'] = 'Vous n\'avez rien réussi à collecter et vous avez perdu de l\'expérience pour avoir perdu du temps..', -- Notification
            ['collectanimalfailnoxp'] = 'Vous n\'avez rien réussi à collecter..', -- Notification
            ['nobottle'] = 'Vous n\'avez rien pour mettre votre alcool en bouteille..', -- Notification
            ['enoughbottle'] = 'Vous n\'avez pas assez de bouteilles avec vous..', -- Notification
            ['checkeggs'] = 'Vérification des Œufs..', -- Barre de progression
            ['milkcow'] = 'Traite de la Vache..', -- Barre de progression
            ['petdog'] = 'Caresser le Chien..', -- Barre de progression
            ['petpig'] = 'Caresser le Cochon..', -- Barre de progression
            ['bottle'] = 'Mise en Bouteille du Lait..', -- Barre de progression
        },
        Troughs = {
            ['nobale'] = 'Vous devez porter une botte de foin pour remplir les auges..', -- Notification
            ['refillxp'] = 'Vous avez rempli une auge et gagné un peu d\'expérience !', -- Notification
            ['refillnoxp'] = 'Vous avez rempli une auge !', -- Notification
            ['alreadyrefilledpig'] = 'Vous avez déjà rempli cette auge, revenez dans ('..Config.Farming.Troughs.Pig.Cooldown..') minutes..', -- Notification
            ['alreadyrefilledcow'] = 'Vous avez déjà rempli cette auge, revenez dans ('..Config.Farming.Troughs.Cow.Cooldown..') minutes..', -- Notification
            ['alreadyrefilledchicken'] = 'Vous avez déjà rempli cette auge, revenez dans ('..Config.Farming.Troughs.Chicken.Cooldown..') minutes..', -- Notification
            ['filltrough'] = 'Remplissage de l\'Auge..', -- Barre de progression
        },
        Planting = {
            ['plantedseednoxp'] = 'Vous avez planté une graine avec succès !', -- Notification
            ['plantedseedxp'] = 'Vous avez planté une graine avec succès et gagné de l\'expérience !', -- Notification
            ['tooclose'] = 'Vous êtes trop près d\'une autre plante..', -- Notification
            ['wrongsoil'] = 'Vous ne pouvez pas planter ici, cherchez un sol plus fertile..', -- Notification
            ['harvestxp'] = 'Vous avez récolté des cultures avec succès et gagné de l\'expérience !', -- Notification
            ['harvestnoxp'] = 'Vous avez récolté des cultures avec succès !', -- Notification
            ['destroyedcrop'] = 'Vous avez détruit des cultures avec succès !', -- Notification
            ['notoolplant'] = 'Vous ne pouvez pas planter des graines sans un '..Config.Farming.Planting.Crops.Required.label..'..', -- Notification
            ['notoolharvest'] = 'Vous ne pouvez pas récolter sans un '..Config.Farming.Planting.Harvest.Required.label..'..', -- Notification
            ['notooldestroy'] = 'Vous ne pouvez pas détruire sans un '..Config.Farming.Planting.Destroy.Required.label..'..', -- Notification
            ['nofertilizer'] = 'Vous ne pouvez pas nourrir les plantes sans '..Config.Farming.Planting.Feed.Required.label..'..', -- Notification
            ['nowater'] = 'Vous ne pouvez pas arroser les plantes sans '..Config.Farming.Planting.Water.Required.label..'..', -- Notification
            ['harvestheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête du menu
            ['harvestheader'] = 'Récolter la Culture', -- En-tête du menu
            ['harvestheadericon'] = 'fa-solid fa-scissors', -- Icône d'en-tête du menu
            ['feedheader'] = 'Nourrir la Culture', -- En-tête du menu
            ['feedheadericon'] = 'fa-solid fa-bottle-water', -- Icône d'en-tête du menu
            ['waterheader'] = 'Arroser la Culture', -- En-tête du menu
            ['waterheadericon'] = 'fa-solid fa-droplet', -- Icône d'en-tête du menu
            ['destroyheader'] = 'Détruire la Culture', -- En-tête du menu
            ['destroyheadericon'] = 'fa-solid fa-fire', -- Icône d'en-tête du menu
            ['plantseed'] = 'Plantation d\'une Graine..', -- Barre de progression
            ['harvestcrop'] = 'Récolte des Cultures..', -- Barre de progression
            ['destroycrop'] = 'Destruction des Cultures..', -- Barre de progression
            ['feedcrop'] = 'Nourriture des Cultures..', -- Barre de progression
            ['watercrop'] = 'Arrosage des Cultures..', -- Barre de progression
        },
        Objects = {
            ['nocan'] = 'Vous n\'avez pas de '..Config.Farming.Objects.Water.Required.label..' vide à remplir..', -- Notification
            ['nobale'] = 'Vous ne portez pas de botte de foin..', -- Notification
            ['norefill'] = 'Il semble que tous les animaux ont été nourris, revenez plus tard..', -- Notification
            ['collectedbale'] = 'Vous avez ramassé une Botte de Foin !', -- Notification
            ['returnedbale'] = 'Vous avez rendu une Botte de Foin !', -- Notification
            ['collectedpail'] = 'Vous avez ramassé un '..Config.Farming.Animals.Cow.Required.label..' !', -- Notification
            ['waterfail'] = 'Vous devez être dans l\'eau pour remplir votre '..Config.Farming.Objects.Water.Required.label..'..', -- Notification
            ['watersuccess'] = 'Vous avez rempli votre '..Config.Farming.Objects.Water.Required.label..' !', -- Notification
            ['sacksuccess'] = 'Vous avez collecté des '..Config.Farming.Objects.Sack.Return.label..'s !', -- Notification
            ['cratesuccess'] = 'Vous avez collecté des '..Config.Farming.Objects.Crate.Return.label..'s !', -- Notification
            ['collectpail'] = 'Ramassage du Seau à Traire..', -- Barre de progression
            ['collectbale'] = 'Ramassage de la Botte de Foin..', -- Barre de progression
            ['returnbale'] = 'Retour de la Botte de Foin..', -- Barre de progression
            ['collectwater'] = 'Collecte d\'Eau..', -- Barre de progression
            ['collectsack'] = 'Collecte de Sacs..', -- Barre de progression
            ['collectcrates'] = 'Collecte de Caisses..', -- Barre de progression
        },
        Farmer = {
            ['farmerheader'] = 'Fermier', -- En-tête du menu
            ['farmerheadertext'] = 'Achetez des fournitures agricoles et plus encore !', -- Texte d'en-tête
            ['farmerheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['storeheader'] = 'Ouvrir le Magasin', -- En-tête du menu
            ['storeheadertext'] = 'Achetez des fournitures agricoles ici !', -- Texte d'en-tête
            ['storeheadericon'] = 'fa-solid fa-shop', -- Icône d'en-tête
            ['infoheader'] = 'Brassage', -- En-tête du menu
            ['infoheadertext'] = 'Obtenez des informations vitales sur le brassage ici !', -- Texte d'en-tête
            ['infoheadericon'] = 'fa-solid fa-beer-mug-empty', -- Icône d'en-tête
            ['timer'] = 'Ma journée de travail est terminée. Revenez entre '..Config.Stores.Farmer.Open..' et '..Config.Stores.Farmer.Close..'..', -- Notification
            ['cantemail'] = 'Vous avez déjà reçu l\'information, vérifiez votre téléphone..', -- Notification
            ['emailsent'] = 'L\'information a été demandée, veuillez attendre un email !', -- Notification
            ['gpsset'] = 'Un point de repère a été envoyé sur votre GPS.', -- Notification
        },
        Packing = {
            ['packingheader'] = 'Emballer les Cultures', -- En-tête du menu
            ['packingheadertext'] = 'Emballez les cultures pour les livraisons ici !', -- Texte d'en-tête
            ['packingheadericon'] = 'fas fa-box-open', -- Icône d'en-tête
            ['barleyheader'] = 'Orge', -- En-tête du menu
            ['barleyheadertext'] = 'Requis:</p>1x '..Config.Packing.Sack.Required.label..'</p>'..Config.Packing.Sack.Barley.Required.amount..'x '..Config.Packing.Sack.Barley.Required.label, -- Texte d'en-tête
            ['barleyheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['maizeheader'] = 'Maïs', -- En-tête du menu
            ['maizeheadertext'] = 'Requis:</p>1x '..Config.Packing.Sack.Required.label..'</p>'..Config.Packing.Sack.Maize.Required.amount..'x '..Config.Packing.Sack.Maize.Required.label, -- Texte d'en-tête
            ['maizeheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['potatoheader'] = 'Pommes de Terre', -- En-tête du menu
            ['potatoheadertext'] = 'Requis:</p>1x '..Config.Packing.Sack.Required.label..'</p>'..Config.Packing.Sack.Potato.Required.amount..'x '..Config.Packing.Sack.Potato.Required.label, -- Texte d'en-tête
            ['potatoheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['mushroomheader'] = 'Champignons', -- En-tête du menu
            ['mushroomheadertext'] = 'Requis:</p>1x '..Config.Packing.Sack.Required.label..'</p>'..Config.Packing.Sack.Mushroom.Required.amount..'x '..Config.Packing.Sack.Mushroom.Required.label, -- Texte d'en-tête
            ['mushroomheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['appleheader'] = 'Pommes', -- En-tête du menu
            ['appleheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Apple.Required.amount..'x '..Config.Packing.Crate.Apple.Required.label, -- Texte d'en-tête
            ['appleheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['orangeheader'] = 'Oranges', -- En-tête du menu
            ['orangeheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Orange.Required.amount..'x '..Config.Packing.Crate.Orange.Required.label, -- Texte d'en-tête
            ['orangeheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['lemonheader'] = 'Citrons', -- En-tête du menu
            ['lemonheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Lemon.Required.amount..'x '..Config.Packing.Crate.Lemon.Required.label, -- Texte d'en-tête
            ['lemonheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['limeheader'] = 'Limes', -- En-tête du menu
            ['limeheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Lime.Required.amount..'x '..Config.Packing.Crate.Lime.Required.label, -- Texte d'en-tête
            ['limeheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['lettuceheader'] = 'Laitue', -- En-tête du menu
            ['lettuceheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Lettuce.Required.amount..'x '..Config.Packing.Crate.Lettuce.Required.label, -- Texte d'en-tête
            ['lettuceheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['cactusfruitheader'] = 'Fruits de Cactus', -- En-tête du menu
            ['cactusfruitheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.CactusFruit.Required.amount..'x '..Config.Packing.Crate.CactusFruit.Required.label, -- Texte d'en-tête
            ['cactusfruitheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['tomatoheader'] = 'Tomates', -- En-tête du menu
            ['tomatoheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Tomato.Required.amount..'x '..Config.Packing.Crate.Tomato.Required.label, -- Texte d'en-tête
            ['tomatoheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['strawberryheader'] = 'Fraises', -- En-tête du menu
            ['strawberryheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Strawberry.Required.amount..'x '..Config.Packing.Crate.Strawberry.Required.label, -- Texte d'en-tête
            ['strawberryheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['blueberryheader'] = 'Myrtilles', -- En-tête du menu
            ['blueberryheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Blueberry.Required.amount..'x '..Config.Packing.Crate.Blueberry.Required.label, -- Texte d'en-tête
            ['blueberryheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['pineappleheader'] = 'Ananas', -- En-tête du menu
            ['pineappleheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Pineapple.Required.amount..'x '..Config.Packing.Crate.Pineapple.Required.label, -- Texte d'en-tête
            ['pineappleheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['milkheader'] = 'Lait', -- En-tête du menu
            ['milkheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Milk.Required.amount..'x '..Config.Packing.Crate.Milk.Required.label, -- Texte d'en-tête
            ['milkheadericon'] = 'fa-solid fa-cow', -- Icône d'en-tête
            ['eggheader'] = 'Œufs', -- En-tête du menu
            ['eggheadertext'] = 'Requis:</p>1x '..Config.Packing.Crate.Required.label..'</p>'..Config.Packing.Crate.Egg.Required.amount..'x '..Config.Packing.Crate.Egg.Required.label, -- Texte d'en-tête
            ['eggheadericon'] = 'fa-solid fa-egg', -- Icône d'en-tête
            ['nopacking'] = 'Vous n\'avez rien pour emballer les cultures..', -- Notification
            ['enoughitems'] = 'Vous n\'avez pas assez de cultures à emballer..', -- Notification
            ['anyitems'] = 'Vous n\'avez aucune culture à emballer..', -- Notification
            ['packedxp'] = 'Vous avez emballé des cultures et gagné un peu d\'expérience !', -- Notification
            ['packednoxp'] = 'Vous avez emballé des cultures !', -- Notification
            ['packingcrops'] = 'Emballage des Cultures..', -- Barre de progression
        },
        Warehouse = {
            ['warehouseheader'] = 'Entrepôt', -- En-tête du menu
            ['warehouseheadertext'] = 'Achetez ou vendez des cultures ici !', -- Texte d'en-tête
            ['warehouseheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['buyheader'] = 'Acheter des Cultures', -- En-tête du menu
            ['buyheadertext'] = 'Achetez vos cultures ici !', -- Texte d'en-tête
            ['buyheadericon'] = 'fa-solid fa-shop', -- Icône d'en-tête
            ['sellheader'] = 'Vendre des Cultures', -- En-tête du menu
            ['sellheadertext'] = 'Vendez vos cultures ici !', -- Texte d'en-tête
            ['sellheadericon'] = 'fa-solid fa-money-bill-wheat', -- Icône d'en-tête
            ['barleyheader'] = 'Sac d\'Orge', -- En-tête du menu
            ['barleybuyheader'] = 'Orge', -- En-tête du menu
            ['barleyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Barley, -- Texte d'en-tête
            ['barleybuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Barley, -- Texte d'en-tête
            ['barleyheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['maizeheader'] = 'Sac de Maïs', -- En-tête du menu
            ['maizebuyheader'] = 'Maïs', -- En-tête du menu
            ['maizeheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Maize, -- Texte d'en-tête
            ['maizebuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Maize, -- Texte d'en-tête
            ['maizeheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['potatoheader'] = 'Sac de Pommes de Terre', -- En-tête du menu
            ['potatobuyheader'] = 'Pommes de Terre', -- En-tête du menu
            ['potatoheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Potato, -- Texte d'en-tête
            ['potatobuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Potato, -- Texte d'en-tête
            ['potatoheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['mushroomheader'] = 'Sac de Champignons', -- En-tête du menu
            ['mushroombuyheader'] = 'Champignons', -- En-tête du menu
            ['mushroomheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Mushroom, -- Texte d'en-tête
            ['mushroombuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Mushroom, -- Texte d'en-tête
            ['mushroomheadericon'] = 'fa-solid fa-wheat-awn', -- Icône d'en-tête
            ['appleheader'] = 'Caisse de Pommes', -- En-tête du menu
            ['applebuyheader'] = 'Pommes', -- En-tête du menu
            ['appleheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Apple, -- Texte d'en-tête
            ['applebuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Apple, -- Texte d'en-tête
            ['appleheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['orangeheader'] = 'Caisse d\'Oranges', -- En-tête du menu
            ['orangebuyheader'] = 'Oranges', -- En-tête du menu
            ['orangeheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Orange, -- Texte d'en-tête
            ['orangebuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Orange, -- Texte d'en-tête
            ['orangeheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['lemonheader'] = 'Caisse de Citrons', -- En-tête du menu
            ['lemonbuyheader'] = 'Citrons', -- En-tête du menu
            ['lemonheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Lemon, -- Texte d'en-tête
            ['lemonbuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Lemon, -- Texte d'en-tête
            ['lemonheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['limeheader'] = 'Caisse de Limes', -- En-tête du menu
            ['limebuyheader'] = 'Limes', -- En-tête du menu
            ['limeheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Lime, -- Texte d'en-tête
            ['limebuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Lime, -- Texte d'en-tête
            ['limeheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['lettuceheader'] = 'Caisse de Laitue', -- En-tête du menu
            ['lettucebuyheader'] = 'Laitue', -- En-tête du menu
            ['lettuceheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Lettuce, -- Texte d'en-tête
            ['lettucebuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Lettuce, -- Texte d'en-tête
            ['lettuceheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['cactusfruitheader'] = 'Caisse de Fruits de Cactus', -- En-tête du menu
            ['cactusfruitbuyheader'] = 'Fruits de Cactus', -- En-tête du menu
            ['cactusfruitheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.CactusFruit, -- Texte d'en-tête
            ['cactusfruitbuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.CactusFruit, -- Texte d'en-tête
            ['cactusfruitheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['tomatoheader'] = 'Caisse de Tomates', -- En-tête du menu
            ['tomatobuyheader'] = 'Tomates', -- En-tête du menu
            ['tomatoheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Tomato, -- Texte d'en-tête
            ['tomatobuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Tomato, -- Texte d'en-tête
            ['tomatoheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['strawberryheader'] = 'Caisse de Fraises', -- En-tête du menu
            ['strawberrybuyheader'] = 'Fraises', -- En-tête du menu
            ['strawberryheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Strawberry, -- Texte d'en-tête
            ['strawberrybuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Strawberry, -- Texte d'en-tête
            ['strawberryheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['blueberryheader'] = 'Caisse de Myrtilles', -- En-tête du menu
            ['blueberrybuyheader'] = 'Myrtilles', -- En-tête du menu
            ['blueberryheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Blueberry, -- Texte d'en-tête
            ['blueberrybuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Blueberry, -- Texte d'en-tête
            ['blueberryheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['pineappleheader'] = 'Caisse d\'Ananas', -- En-tête du menu
            ['pineapplebuyheader'] = 'Ananas', -- En-tête du menu
            ['pineappleheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Pineapple, -- Texte d'en-tête
            ['pineapplebuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Pineapple, -- Texte d'en-tête
            ['pineappleheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['milkheader'] = 'Caisse de Lait', -- En-tête du menu
            ['milkbuyheader'] = 'Lait', -- En-tête du menu
            ['milkheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Milk, -- Texte d'en-tête
            ['milkbuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Milk, -- Texte d'en-tête
            ['milkheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['eggheader'] = 'Caisse d\'Œufs', -- En-tête du menu
            ['eggbuyheader'] = 'Œufs', -- En-tête du menu
            ['eggheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Sell.Egg, -- Texte d'en-tête
            ['eggbuyheadertext'] = 'Prix: $'..Config.Stores.Warehouse.Prices.Buy.Egg, -- Texte d'en-tête
            ['eggheadericon'] = 'fa-solid fa-apple-whole', -- Icône d'en-tête
            ['inputtext'] = 'Acheter des Cultures', -- Texte d'entrée
            ['inputamount'] = 'quantité', -- Texte d'entrée
            ['timer'] = 'Ma journée de travail est terminée. Revenez entre '..Config.Stores.Warehouse.Open..' et '..Config.Stores.Warehouse.Close..'..', -- Notification
            ['sold'] = 'Vous avez vendu des cultures à l\'entrepôt !', -- Notification
            ['nosell'] = 'Vous n\'avez rien à vendre..', -- Notification
            ['enoughmoney'] = 'Vous n\'avez pas assez d\'argent..', -- Notification
            ['nostock'] = 'Nous n\'avons pas assez en stock. Quantité:', -- Notification
        },
        Brewing = {
            ['stillheader'] = 'Alambic', -- En-tête du menu
            ['stillheadertext'] = 'Brassez de l\'alcool clandestin ici !', -- Texte d'en-tête
            ['stillheadericon'] = 'fa-solid fa-fire-burner', -- Icône d'en-tête
            ['mashheader'] = 'Préparer la Purée', -- En-tête du menu
            ['mashheadertext'] = 'Préparez votre purée de brassage ici !', -- Texte d'en-tête
            ['mashheadericon'] = 'fa-solid fa-kitchen-set', -- Icône d'en-tête
            ['moonshinemashheader'] = 'Purée de Moonshine', -- En-tête du menu
            ['moonshinemashheadertext'] = 'Requis:</p>1x '..Config.Brewing.Moonshine.Mash.Required['1'].label..'</p>'..Config.Brewing.Moonshine.Mash.Required['2'].amount..'x '..Config.Brewing.Moonshine.Mash.Required['2'].label..'</p>'..Config.Brewing.Moonshine.Mash.Required['3'].amount..'x '..Config.Brewing.Moonshine.Mash.Required['3'].label..'</p>'..Config.Brewing.Moonshine.Mash.Required['4'].amount..'x '..Config.Brewing.Moonshine.Mash.Required['4'].label, -- Texte d'en-tête
            ['moonshinemashheadericon'] = 'fa-solid fa-fire-burner', -- Icône d'en-tête
            ['vodkamashheader'] = 'Purée de Vodka', -- En-tête du menu
            ['vodkamashheadertext'] = 'Requis:</p>1x '..Config.Brewing.Vodka.Mash.Required['1'].label..'</p>'..Config.Brewing.Vodka.Mash.Required['2'].amount..'x '..Config.Brewing.Vodka.Mash.Required['2'].label..'</p>'..Config.Brewing.Vodka.Mash.Required['3'].amount..'x '..Config.Brewing.Vodka.Mash.Required['3'].label..'</p>'..Config.Brewing.Vodka.Mash.Required['4'].amount..'x '..Config.Brewing.Vodka.Mash.Required['4'].label, -- Texte d'en-tête
            ['vodkamashheadericon'] = 'fa-solid fa-fire-burner', -- Icône d'en-tête
            ['fermentheader'] = 'Fermenter l\'Alcool', -- En-tête du menu
            ['fermentheadertext'] = 'Fermentez votre alcool ici !', -- Texte d'en-tête
            ['fermentheadericon'] = 'fa-solid fa-bottle-droplet', -- Icône d'en-tête
            ['moonshinefermheader'] = 'Fermenter le Moonshine', -- En-tête du menu
            ['moonshinefermheadertext'] = 'Requis:</p>'..Config.Brewing.Moonshine.Ferment.Required['1'].amount..'x '..Config.Brewing.Moonshine.Ferment.Required['1'].label..'</p>'..Config.Brewing.Moonshine.Ferment.Required['2'].amount..'x '..Config.Brewing.Moonshine.Ferment.Required['2'].label, -- Texte d'en-tête
            ['moonshinefermheadericon'] = 'fa-solid fa-fire-burner', -- Icône d'en-tête
            ['vodkafermheader'] = 'Fermenter la Vodka', -- En-tête du menu
            ['vodkafermheadertext'] = 'Requis:</p>'..Config.Brewing.Vodka.Ferment.Required['1'].amount..'x '..Config.Brewing.Vodka.Ferment.Required['1'].label..'</p>'..Config.Brewing.Vodka.Ferment.Required['2'].amount..'x '..Config.Brewing.Vodka.Ferment.Required['2'].label, -- Texte d'en-tête
            ['vodkafermheadericon'] = 'fa-solid fa-fire-burner', -- Icône d'en-tête
            ['distillheader'] = 'Distiller l\'Alcool Fermenté', -- En-tête du menu
            ['distillheadertext'] = 'Distillez votre alcool fermenté ici !', -- Texte d'en-tête
            ['distillheadericon'] = 'fa-solid fa-bottle-droplet', -- Icône d'en-tête
            ['moonshinedistheader'] = 'Distiller le Moonshine', -- En-tête du menu
            ['moonshinedistheadertext'] = 'Requis:</p>1x '..Config.Brewing.Moonshine.Distill.Required['1'].label..'</p>'..Config.Brewing.Moonshine.Distill.Required['2'].amount..'x '..Config.Brewing.Moonshine.Distill.Required['2'].label, -- Texte d'en-tête
            ['moonshinedistheadericon'] = 'fa-solid fa-fire-burner', -- Icône d'en-tête
            ['vodkadistheader'] = 'Distiller la Vodka', -- En-tête du menu
            ['vodkadistheadertext'] = 'Requis:</p>1x '..Config.Brewing.Vodka.Distill.Required['1'].label..'</p>'..Config.Brewing.Vodka.Distill.Required['2'].amount..'x '..Config.Brewing.Vodka.Distill.Required['2'].label, -- Texte d'en-tête
            ['vodkadistheadericon'] = 'fa-solid fa-fire-burner', -- Icône d'en-tête
            ['level'] = 'Vous n\'avez aucune idée de ce qu\'il faut faire ici.. Gagnez d\'abord un peu d\'expérience..', -- Notification
            ['nobucket'] = 'Vous n\'avez rien pour mettre votre mélange..', -- Notification
            ['wrongitems'] = 'Vous n\'avez pas les bons objets, vérifiez vos poches..', -- Notification
            ['mashxp'] = 'Vous avez préparé un mélange de purée et gagné un peu d\'expérience !', -- Notification
            ['mashnoxp'] = 'Vous avez préparé un mélange de purée !', -- Notification
            ['fermxp'] = 'Vous avez fermenté de l\'alcool et gagné un peu d\'expérience !', -- Notification
            ['fermnoxp'] = 'Vous avez fermenté de l\'alcool !', -- Notification
            ['nobottle'] = 'Vous n\'avez rien pour mettre votre alcool en bouteille..', -- Notification
            ['enoughbottle'] = 'Vous n\'avez pas assez de bouteilles avec vous..', -- Notification
            ['prepmash'] = 'Préparation de la Purée..', -- Barre de progression
            ['waitmash'] = 'Attente de la Purée..', -- Barre de progression
            ['prepferm'] = 'Versement de la Purée dans le Baril..', -- Barre de progression
            ['waitferm'] = 'Attente de la Fermentation de l\'Alcool..', -- Barre de progression
            ['distill'] = 'Distillation de l\'Alcool..', -- Barre de progression
            ['bottle'] = 'Mise en Bouteille de l\'Alcool..', -- Barre de progression
        }
    },
    Shared = {
        ['returnmenu'] = 'Retour', -- En-tête du menu
        ['returnmenuicon'] = 'fa-solid fa-backward', -- Icône d'en-tête du menu
        ['exitmenu'] = 'Quitter', -- En-tête du menu
        ['exitmenuicon'] = 'fa-solid fa-circle-xmark', -- Icône d'en-tête du menu
        ['cancelled'] = 'Action annulée..', -- Notification
        ['noinvent'] = 'Il semble que vos poches sont pleines..', -- Notification
        ['outrange'] = 'Il semble que vous êtes trop loin..', -- Notification
        ['isbusy'] = 'Vous êtes déjà en train de faire quelque chose..', -- Notification
    }
}