INSERT INTO `mdt_offenses` (`label`, `type`, `category`, `description`, `time`, `fine`, `points`) VALUES
    -- INFRACTIONS CONTRE LES PERSONNES
    ('Agression', 'délit', 'INFRACTIONS CONTRE LES PERSONNES', 'Attaque illégale sur une autre personne.', 30, 1000, 0),
    ('Enlèvement', 'crime', 'INFRACTIONS CONTRE LES PERSONNES', 'Capture et séquestration illégale dune personne par la force.', 360, 20000, 0),
    ('Homicide involontaire', 'crime', 'INFRACTIONS CONTRE LES PERSONNES', 'Fait de tuer une personne sans intention lors de la commission d un délit.', 180, 15000, 0),
    ('Meurtre', 'crime', 'INFRACTIONS CONTRE LES PERSONNES', 'Homicide volontaire et prémédité d un être humain.', 999, 50000, 0),
    ('Crime haineux', 'crime', 'INFRACTIONS CONTRE LES PERSONNES', 'Crime motivé par des préjugés raciaux, sexuels ou autres.', 180, 10000, 0),
    ('Coups et blessures', 'délit', 'INFRACTIONS CONTRE LES PERSONNES', 'Usage de la force envers autrui causant des blessures ou contacts offensants.', 60, 3000, 0),
    ('Harcèlement criminel', 'délit', 'INFRACTIONS CONTRE LES PERSONNES', 'Suivre ou harceler de façon répétée une personne avec menaces.', 90, 5000, 0),
    ('Traite d êtres humains', 'crime', 'INFRACTIONS CONTRE LES PERSONNES', 'Trafic illégal d êtres humains à des fins de travail forcé ou d exploitation sexuelle.', 720, 50000, 0),
    ('Agression sexuelle', 'crime', 'INFRACTIONS CONTRE LES PERSONNES', 'Acte par lequel une personne touche sexuellement une autre personne sans son consentement.', 360, 20000, 0),
    ('Harcèlement', 'délit', 'INFRACTIONS CONTRE LES PERSONNES', 'Adoption d un comportement non désiré qui alarme ou importune gravement une autre personne, sans motif légitime.', 0, 500, 0),

    -- INFRACTIONS IMPLIQUANT LE VOL
    ('Vol simple', 'délit', 'INFRACTIONS IMPLIQUANT LE VOL', 'Appropriation illégale de biens personnels.', 60, 2000, 0),
    ('Vol de véhicule', 'crime', 'INFRACTIONS IMPLIQUANT LE VOL', 'Vol d un véhicule automobile.', 180, 10000, 0),
    ('Cambriolage', 'crime', 'INFRACTIONS IMPLIQUANT LE VOL', 'Entrée par effraction dans un bâtiment avec l intention de commettre un crime ou un vol.', 90, 5000, 0),
    ('Vol à l étalage', 'délit', 'INFRACTIONS IMPLIQUANT LE VOL', 'Vol de marchandises dans un magasin.', 30, 1000, 0),
    ('Vol à main armée', 'crime', 'INFRACTIONS IMPLIQUANT LE VOL', 'Vol avec usage d une arme.', 360, 25000, 0),
    ('Détournement de fonds', 'crime', 'INFRACTIONS IMPLIQUANT LE VOL', 'Vol ou détournement de fonds confiés à sa garde ou appartenant à son employeur.', 180, 15000, 0),
    ('Recel de biens volés', 'délit', 'INFRACTIONS IMPLIQUANT LE VOL', 'Réception, achat ou possession de biens que l''on sait être volés.', 90, 4000, 0),
    ('Vol d''identité', 'crime', 'INFRACTIONS IMPLIQUANT LE VOL', 'Acquisition et utilisation frauduleuses des informations d''identification privées d''une personne.', 180, 10000, 0),
    ('Revente illégale de billets', 'délit', 'INFRACTIONS IMPLIQUANT LE VOL', 'Vente de billets pour un événement sans licence appropriée et souvent à un prix supérieur à leur valeur nominale.', 0, 200, 0),

    -- INFRACTIONS IMPLIQUANT LA FRAUDE
    ('Fraude électronique', 'crime', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Fraude impliquant l utilisation de communications électroniques.', 180, 15000, 0),
    ('Fraude à l assurance', 'crime', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Falsification ou exagération des faits d un accident auprès d une compagnie d assurance.', 180, 10000, 0),
    ('Fraude boursière', 'crime', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Pratiques frauduleuses sur les marchés boursiers, y compris le délit d initié.', 360, 25000, 0),
    ('Fraude à la carte bancaire', 'crime', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Utilisation non autorisée d une carte bancaire pour obtenir des biens.', 90, 5000, 0),
    ('Évasion fiscale', 'crime', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Non-paiement ou sous-paiement illégal d impôts.', 180, 10000, 0),
    ('Fraude aux soins de santé', 'crime', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Dépôt de réclamations malhonnêtes en matière de soins de santé pour obtenir un profit.', 180, 15000, 0),
    ('Fraude postale', 'crime', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Utilisation des services postaux pour commettre une fraude.', 180, 10000, 0),
    ('Fausse déclaration', 'délit', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Fourniture délibérée de fausses informations dans une transaction commerciale.', 90, 3000, 0),
    ('Publicité mensongère', 'délit', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Publicité trompeuse ou mensongère de produits ou services.', 30, 2000, 0),
    ('Hameçonnage', 'délit', 'INFRACTIONS IMPLIQUANT LA FRAUDE', 'Tentative d''obtention d''informations sensibles telles que noms d''utilisateur, mots de passe et coordonnées bancaires en se faisant passer pour une entité de confiance dans une communication électronique.', 0, 500, 0),

    -- INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS
    ('Vandalisme', 'délit', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Destruction ou dégradation délibérée de biens.', 30, 1000, 0),
    ('Incendie criminel', 'crime', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Acte criminel consistant à mettre délibérément le feu à des biens.', 360, 20000, 0),
    ('Tags', 'délit', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Inscriptions ou dessins illégaux sur un mur ou une surface dans un lieu public.', 60, 2500, 0),
    ('Méfait criminel', 'délit', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Dommage intentionnel ou conscient aux biens d autrui.', 90, 3000, 0),
    ('Intrusion avec dommages', 'délit', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Pénétration sans autorisation sur la propriété d autrui avec dégradations.', 30, 2000, 0),
    ('Dépôt illégal de déchets', 'délit', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Élimination illégale de déchets dans des zones non désignées.', 90, 5000, 0),
    ('Destruction de panneaux', 'délit', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Acte de destruction ou de dégradation de panneaux routiers ou autres signalisations publiques.', 0, 500, 0),
    ('Abandon de déchets', 'délit', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Jet négligent de déchets ou autres matériaux sur la voie publique ou propriété privée.', 0, 250, 0),
    ('Dégradation des services publics', 'crime', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Endommagement intentionnel ou interférence avec les services des fournisseurs d''utilité publique.', 180, 10000, 0),
    ('Sabotage', 'crime', 'INFRACTIONS IMPLIQUANT DES DOMMAGES AUX BIENS', 'Destruction, endommagement ou obstruction délibérée, particulièrement dans un but politique ou militaire.', 360, 25000, 0),

    -- INFRACTIONS CONTRE L'ADMINISTRATION PUBLIQUE
    ('Corruption', 'crime', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Offre, don, réception ou sollicitation de valeurs pour influencer les actions d un officiel.', 180, 15000, 0),
    ('Parjure', 'crime', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Fait de mentir délibérément sous serment devant un tribunal.', 180, 10000, 0),
    ('Entrave à la justice', 'crime', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Obstruction au travail des procureurs ou autres officiels.', 180, 10000, 0),
    ('Corruption publique', 'crime', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Abus de fonction publique à des fins personnelles.', 360, 25000, 0),
    ('Falsification de documents', 'délit', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Modification, dissimulation ou destruction de documents officiels.', 90, 5000, 0),
    ('Subornation de témoin', 'crime', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Tentative de modifier ou d''empêcher le témoignage de témoins dans le cadre de procédures pénales ou civiles.', 240, 15000, 0),
    ('Lobbying illégal', 'délit', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Exercer des activités de lobbying sans enregistrement approprié ou lorsque spécifiquement interdit.', 120, 8000, 0),
    ('Fraude électorale', 'crime', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Interférence illégale dans le processus électoral.', 240, 20000, 0),
    ('Détournement de fonds publics', 'crime', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Utilisation de fonds publics à des fins non autorisées, illégales ou contraires à l''éthique.', 180, 15000, 0),
    ('Divulgation non autorisée d''informations confidentielles', 'délit', 'INFRACTIONS CONTRE L ADMINISTRATION PUBLIQUE', 'Révélation inappropriée d''informations confidentielles ou classifiées sans autorisation.', 0, 1000, 0),

    -- INFRACTIONS CONTRE L'ORDRE PUBLIQUE
    ('Trouble à l ordre public', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Comportement perturbant la paix publique, incluant bagarres, bruits excessifs ou troubles publics.', 30, 1000, 0),
    ('Rassemblement illégal', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Regroupement de personnes dans l intention de troubler l ordre public.', 60, 3000, 0),
    ('Ivresse publique', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Présence dans des lieux publics en état d ébriété manifeste, représentant un danger.', 0, 500, 0),
    ('Incitation à l émeute', 'crime', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Encouragement ou participation à des comportements violents menant à des troubles de masse.', 90, 7000, 0),
    ('Manifestation illégale', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Manifestation sans autorisation ou en violation des restrictions légales.', 30, 2000, 0),
    ('Vagabondage', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Présence prolongée dans un lieu public sans motif légitime.', 0, 250, 0),
    ('Violation du couvre-feu', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Non-respect des règlements de couvre-feu imposés par le gouvernement.', 0, 300, 0),
    ('Errance', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Vie dans les espaces publics sans domicile fixe ni emploi.', 30, 1000, 0),
    ('Nudité publique', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Exhibition volontaire dans un espace public.', 60, 2000, 0),
    ('Jeux d argent illégaux', 'délit', 'INFRACTIONS CONTRE L ORDRE PUBLIQUE', 'Organisation ou participation à des jeux d argent sans autorisation légale.', 90, 5000, 0),

    -- INFRACTIONS CONTRE LA SANTÉ ET LA MORALE
    ('Possession de drogue', 'délit', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Possession de drogues illégales ou de substances contrôlées sans ordonnance.', 60, 2000, 0),
    ('Prostitution', 'délit', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Exercice, sollicitation ou organisation d activités sexuelles contre rémunération.', 90, 3000, 0),
    ('Vente de substances illégales', 'crime', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Vente ou distribution de drogues illégales ou autres substances interdites.', 180, 10000, 0),
    ('Attentat à la pudeur', 'délit', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Actes de nature sexuelle dans des espaces publics ou exhibition inappropriée.', 30, 1000, 0),
    ('Exploitation de jeux d argent', 'crime', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Exploitation ou participation à des activités de jeux d argent illégales.', 180, 15000, 0),
    ('Consommation d alcool par mineur', 'délit', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Consommation ou possession d alcool par des personnes n ayant pas l âge légal.', 0, 500, 0),
    ('Violation de l interdiction de fumer', 'délit', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Fumer dans les zones non-fumeurs ou violation des règlements locaux.', 0, 250, 0),
    ('Feux d artifice illégaux', 'délit', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Possession, utilisation ou vente de feux d artifice sans autorisation.', 30, 2000, 0),
    ('Cruauté envers les animaux', 'délit', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Infliger intentionnellement des souffrances ou négligence envers des animaux.', 90, 5000, 0),
    ('Tatouage illégal', 'délit', 'INFRACTIONS CONTRE LA SANTÉ ET LA MORALE', 'Tatouage sans licence ou sur des mineurs sans consentement légal.', 0, 1000, 0),

    -- INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE
    ('Port d arme sans permis', 'crime', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Possession ou port d une arme à feu sans les permis nécessaires.', 180, 10000, 0),
    ('Possession criminelle d arme classe A', 'crime', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Possession d une arme de classe A, comme une mitrailleuse ou un fusil d assaut.', 360, 20000, 0),
    ('Possession criminelle d arme classe B', 'crime', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Possession d une arme de classe B, comme un fusil à canon scié ou un pistolet.', 180, 15000, 0),
    ('Possession criminelle d arme classe C', 'délit', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Possession d une arme de classe C, comme une carabine ou un fusil de chasse.', 90, 5000, 0),
    ('Possession criminelle d arme classe D', 'délit', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Possession d une arme de classe D, comme un couteau ou une matraque.', 30, 1000, 0),
    ('Mise en danger téméraire', 'crime', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Adopter une conduite qui présente un risque important de blessures physiques graves pour autrui.', 90, 7000, 0),
    ('Infraction au code de la route', 'contravention', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Violation des règles de circulation comme l''excès de vitesse, le non-respect des feux rouges ou le stationnement illégal.', 0, 500, 1),
    ('Chasse illégale', 'délit', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Chasser dans des zones restreintes ou hors saison sans les permis appropriés.', 60, 3000, 0),
    ('Violation du code de la construction', 'délit', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Non-respect des règlements locaux de construction, créant potentiellement des risques pour la sécurité.', 30, 2000, 0),
    ('Conduite en état d''ivresse avec blessures corporelles', 'crime', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Conduire sous l''influence de l''alcool ou de drogues et causer des blessures corporelles.', 180, 15000, 3),
    ('Possession d''explosifs', 'crime', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Possession illégale ou manipulation inappropriée de matières explosives.', 360, 20000, 0),
    ('Déversement de déchets dangereux', 'crime', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Élimination de matières dangereuses d''une manière qui met en danger la santé publique et l''environnement.', 180, 15000, 0),
    ('Décharge négligente d''une arme à feu', 'délit', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Décharge accidentelle d''une arme à feu due à une manipulation imprudente.', 60, 3000, 0),
    ('Transport inapproprié de matières dangereuses', 'crime', 'INFRACTIONS CONTRE LA SÉCURITÉ PUBLIQUE', 'Transport de matières dangereuses sans respect des règles de sécurité et des exigences légales.', 240, 15000, 0),

    -- INFRACTIONS CONTRE LA CONDUITE D'UN VÉHICULE
    ('Conduite sans permis', 'délit', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Conduite d un véhicule sans permis de conduire valide.', 0, 1000, 2),
    ('Conduite avec permis suspendu', 'délit', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Conduite malgré la suspension ou révocation du permis.', 30, 2000, 2),
    ('Délit de fuite', 'crime', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Quitter les lieux d un accident sans fournir ses coordonnées ou porter assistance.', 180, 10000, 3),
    ('Conduite dangereuse', 'délit', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Conduite manifestant un mépris délibéré pour la sécurité.', 60, 3000, 4),
    ('Homicide involontaire au volant', 'crime', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Causer la mort par négligence ou conduite imprudente.', 360, 20000, 0),
    ('Traffic Obstruction', 'contravention', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Obstructing traffic flow intentionally or unintentionally.', 0, 500, 0),
    ('Illegal Street Racing', 'délit', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Participating in unauthorized speed contests on public roads.', 90, 5000, 3),
    ('Conduite en état d ivresse', 'crime', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Conduite d un véhicule sous l influence de l alcool ou de drogues.', 90, 7000, 3),
    ('Failure to Yield', 'contravention', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Failing to yield the right of way to other road users where required.', 0, 250, 1),
    ('Driving with Obstructed View', 'contravention', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Driving a vehicle with objects blocking the drivers view or control.', 0, 300, 0),
    ('Non-respect de la priorité', 'contravention', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Non-respect du droit de passage des autres usagers de la route lorsque requis.', 0, 250, 1),
    ('Visibilité obstruée', 'contravention', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Conduite avec des objets bloquant la visibilité ou le contrôle du conducteur.', 0, 300, 0),
    ('Obstruction du trafic', 'contravention', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Obstruction intentionnelle ou non de la circulation routière.', 0, 500, 0),
    ('Course automobile illégale', 'délit', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Participation à des courses de vitesse non autorisées sur la voie publique.', 90, 5000, 3),
    ('Refus de priorité', 'contravention', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Non-respect de la priorité envers les autres usagers de la route.', 0, 250, 1),
    ('Conduite avec visibilité obstruée', 'contravention', 'INFRACTIONS LIÉES À LA CONDUITE D UN VÉHICULE', 'Conduite d un véhicule avec des objets obstruant la vue ou le contrôle du conducteur.', 0, 300, 0),

    -- INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE
    ('Pêche illégale', 'délit', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Pêche sans permis ou dans des zones interdites.', 30, 2000, 0),
    ('Trafic d espèces sauvages', 'crime', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Exportation ou importation illégale d espèces protégées.', 360, 25000, 0),
    ('Destruction d habitat', 'crime', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Destruction délibérée d environnements abritant la faune.', 180, 15000, 0),
    ('Braconnage', 'crime', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Chasse, mise à mort ou capture illégale d animaux sauvages.', 180, 10000, 0),
    ('Exploitation forestière illégale', 'crime', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Abattage non autorisé d arbres en zone protégée.', 180, 15000, 0),
    ('Perturbation de la faune par pollution sonore', 'délit', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Causer du bruit pouvant nuire au comportement de la faune et à son habitat naturel.', 60, 3000, 0),
    ('Nourrissage illégal de la faune', 'contravention', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Nourrir la faune dans des zones où cela est interdit par la loi.', 0, 500, 0),
    ('Commerce illégal d''animaux de compagnie', 'crime', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Se livrer illégalement à la vente ou à l''achat d''animaux sauvages comme animaux de compagnie.', 360, 20000, 0),
    ('Utilisation de pesticides nocifs', 'délit', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Utiliser des pesticides reconnus comme causant des dommages importants à la faune.', 90, 5000, 0),
    ('Dépôt de déchets dans les réserves naturelles', 'délit', 'INFRACTIONS CONTRE LE BIEN-ÊTRE DE LA FAUNE', 'Jeter des déchets dans une réserve naturelle, affectant négativement la faune.', 30, 2000, 0);